org.gradle.jvmargs=-Xmx4g --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED

android.useAndroidX=true
android.enableJetifier=true
android.gradle.jetifier.ignorelist=core-for-system-modules.jar
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
android.disableLegacyLanguageApiUsageWarning=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
