import 'package:shared_preferences/shared_preferences.dart';
import 'localizations.dart';

/// Dinamik localization helper - delegates to AppLocalizations for single source of truth.
class DynamicLocalizationHelper {
  static String _currentLanguage = 'tr';
  
  static Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString('language_code') ?? prefs.getString('language');
    _currentLanguage = code ?? 'tr';
  }
  
  static Future<void> setLanguage(String language) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', language);
    await prefs.setString('language', language);
    _currentLanguage = language;
  }
  
  static String translate(String key) {
    return AppLocalizations(_currentLanguage).translate(key);
  }
  
  static String getText(Map<String, String> texts) {
    return texts[_currentLanguage] ?? texts['tr'] ?? texts.values.first ?? '';
  }
  
  static String _getText(Map<String, String> texts) {
    return texts[_currentLanguage] ?? texts['tr'] ?? texts.values.first ?? '';
  }
  
  // General keys delegated to AppLocalizations
  static String get statistics => translate('statistics');
  static String get trophies => translate('trophies');
  static String get settings => translate('settings');
  static String get profile => translate('profile');
  static String get leaderboard => translate('leaderboard');
  static String get export => translate('export');
  static String get import => translate('import');
  static String get support => translate('support');
  static String get about => translate('about');
  static String get ok => translate('ok');
  static String get cancel => translate('cancel');
  static String get save => translate('save');
  static String get delete => translate('delete');
  static String get edit => translate('edit');
  static String get back => translate('back');
  static String get next => translate('next');
  static String get previous => translate('previous');
  static String get total => translate('total');
  static String get daily => translate('daily');
  static String get weekly => translate('weekly');
  static String get monthly => translate('monthly');
  static String get year => translate('year');
  static String get theme => translate('theme');
  static String get language => translate('language');
  static String get vibration => translate('vibration');
  static String get sound => translate('sound');
  static String get darkMode => translate('dark_mode');
  static String get lightMode => translate('light_mode');
  static String get reset => translate('reset');
  static String get target => translate('target');
  static String get counter => translate('counter');
  static String get continue_ => translate('continue');
  static String get select => translate('select');
  static String get add => translate('add');
  static String get remove => translate('remove');
  static String get search => translate('search');
  static String get filter => translate('filter');
  static String get sort => translate('sort');
  static String get refresh => translate('refresh');
  static String get loading => translate('loading');
  static String get error => translate('error');
  static String get success => translate('success');
  static String get warning => translate('warning');
  static String get info => translate('info');
  static String get yes => translate('yes');
  static String get no => translate('no');
  static String get share => translate('share');
  static String get copy => translate('copy');
  static String get paste => translate('paste');
  static String get cut => translate('cut');
  static String get undo => translate('undo');
  static String get redo => translate('redo');
  static String get help => translate('help');
  static String get feedback => translate('feedback');
  static String get contact => translate('contact');
  static String get website => translate('website');
  static String get github => translate('github');
  static String get email => translate('email');
  static String get phone => translate('phone');
  static String get address => translate('address');
  static String get name => translate('name');
  static String get description => translate('description');
  static String get date => translate('date');
  static String get time => translate('time');
  static String get hour => translate('hour');
  static String get minute => translate('minute');
  static String get second => translate('second');
  static String get day => translate('day');
  static String get week => translate('week');
  static String get month => translate('month');
  static String get level => translate('level');
  static String get score => translate('score');
  static String get rank => translate('rank');
  static String get achievement => translate('achievement');
  static String get bronze => translate('bronze');
  static String get silver => translate('silver');
  static String get gold => translate('gold');
  static String get diamond => translate('diamond');
  static String get platinum => translate('platinum');
  static String get unlocked => translate('unlocked');
  static String get locked => translate('locked');
  static String get progress => translate('progress');
  static String get completed => translate('completed');
  static String get pending => translate('pending');
  static String get active => translate('active');
  static String get inactive => translate('inactive');
  static String get online => translate('online');
  static String get offline => translate('offline');
  static String get connected => translate('connected');
  static String get disconnected => translate('disconnected');
  static String get sync => translate('sync');
  static String get backup => translate('backup');
  static String get restore => translate('restore');
  static String get download => translate('download');
  static String get upload => translate('upload');
  static String get file => translate('file');
  static String get folder => translate('folder');
  static String get image => translate('image');
  static String get video => translate('video');
  static String get audio => translate('audio');
  static String get document => translate('document');
  static String get camera => translate('camera');
  static String get gallery => translate('gallery');
  static String get permission => translate('permission');
  static String get allow => translate('allow');
  static String get deny => translate('deny');
  static String get enable => translate('enable');
  static String get disable => translate('disable');
  static String get on => translate('on');
  static String get off => translate('off');
  static String get open => translate('open');
  static String get close => translate('close');
  static String get exit => translate('exit');
  static String get quit => translate('quit');
  static String get start => translate('start');
  static String get stop => translate('stop');
  static String get pause => translate('pause');
  static String get play => translate('play');
  static String get retry => translate('retry');
  static String get skip => translate('skip');
  static String get first => translate('first');
  static String get last => translate('last');
  static String get all => translate('all');
  static String get none => translate('none');
  static String get any => translate('any');
  static String get other => translate('other');
  static String get more => translate('more');
  static String get less => translate('less');
  static String get new_ => translate('new');
  static String get old => translate('old');
  static String get recent => translate('recent');
  static String get favorite => translate('favorite');
  static String get bookmark => translate('bookmark');
  static String get history => translate('history');
  static String get log => translate('log');
  static String get report => translate('report');
  static String get analytics => translate('analytics');
  static String get performance => translate('performance');
  static String get quality => translate('quality');
  static String get speed => translate('speed');
  static String get size => translate('size');
  static String get color => translate('color');
  static String get style => translate('style');
  static String get design => translate('design');
  static String get layout => translate('layout');
  static String get format => translate('format');
  static String get option => translate('option');
  static String get setting => translate('setting');
  static String get configuration => translate('configuration');
  static String get preference => translate('preference');
  static String get custom => translate('custom');
  static String get default_ => translate('default');
  static String get automatic => translate('automatic');
  static String get manual => translate('manual');
  static String get secure => translate('secure');
  static String get private_ => translate('private');
  static String get public => translate('public');
  static String get hidden => translate('hidden');
  static String get visible => translate('visible');
  static String get available => translate('available');
  static String get unavailable => translate('unavailable');
  static String get required => translate('required');
  static String get optional => translate('optional');
  static String get recommended => translate('recommended');
  static String get suggested => translate('suggested');
  static String get popular => translate('popular');
  static String get trending => translate('trending');
  static String get featured => translate('featured');
  static String get latest => translate('latest');
  static String get updated => translate('updated');
  static String get created => translate('created');
  static String get modified => translate('modified');
  static String get deleted => translate('deleted');
  static String get archived => translate('archived');
  static String get expired => translate('expired');
  static String get valid => translate('valid');
  static String get invalid => translate('invalid');
  static String get correct => translate('correct');
  static String get incorrect => translate('incorrect');
  static String get true_ => translate('true');
  static String get false_ => translate('false');
  static String get unknown => translate('unknown');
  static String get empty => translate('empty');
  static String get full => translate('full');
  static String get partial => translate('partial');
  static String get complete => translate('complete');
  static String get incomplete => translate('incomplete');
  static String get ready => translate('ready');
  static String get busy => translate('busy');
  static String get idle => translate('idle');
  static String get running => translate('running');
  static String get stopped => translate('stopped');
  static String get whom => translate('whom');
  static String get whom_ => translate('whom');
  static String get whose => translate('whose');
  static String get whose_ => translate('whose');
  static String get where => translate('where');
  static String get why => translate('why');
  static String get how => translate('how');
  static String get what => translate('what');
  static String get which => translate('which');
  static String get who => translate('who');
  static String get timeout => translate('timeout');
  static String get limit => translate('limit');
  static String get exceeded => translate('exceeded');
  static String get insufficient => translate('insufficient');
  static String get enough => translate('enough');
  static String get too => translate('too');
  static String get little => translate('little');
  static String get much => translate('much');
  static String get few => translate('few');
  static String get many => translate('many');
  static String get several => translate('several');
  static String get multiple => translate('multiple');
  static String get single => translate('single');
  static String get double => translate('double');
  static String get triple => translate('triple');
  static String get once => translate('once');
  static String get twice => translate('twice');
  static String get thrice => translate('thrice');
  static String get always => translate('always');
  static String get never => translate('never');
  static String get sometimes => translate('sometimes');
  static String get often => translate('often');
  static String get rarely => translate('rarely');
  static String get usually => translate('usually');
  static String get normally => translate('normally');
  static String get occasionally => translate('occasionally');
  static String get occasionally_ => translate('occasionally');
  static String get seldom => translate('seldom');
  static String get hardly => translate('hardly');
  static String get barely => translate('barely');
  static String get almost => translate('almost');
  static String get nearly => translate('nearly');
  static String get approximately => translate('approximately');
  static String get exactly => translate('exactly');
  static String get precisely => translate('precisely');
  static String get roughly => translate('roughly');
  static String get about_ => translate('about');
  static String get around => translate('around');
  static String get between => translate('between');
  static String get among => translate('among');
  static String get within => translate('within');
  static String get outside => translate('outside');
  static String get inside => translate('inside');
  static String get above => translate('above');
  static String get below => translate('below');
  static String get before => translate('before');
  static String get after => translate('after');
  static String get during => translate('during');
  static String get since => translate('since');
  static String get until => translate('until');
  static String get while_ => translate('while');
  static String get when_ => translate('when');
}
