class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_name': 'Zikirmatik',
      'counter': 'Sayaç',
      'target': 'Hedef',
      'reset': 'Sıfırla',
      'continue': 'Devam Et',
      'cancel': 'İptal',
      'ok': 'Tamam',
      'settings': 'Ayarlar',
      'theme': 'Tema',
      'language': 'Dil',
      'vibration': 'Titreşim',
      'sound': 'Ses',
      'select_zikr': 'Zikir Seç',
      'add_zikr': 'Zikir Ekle',
      'custom_zikrs': 'Özel Zikirler',
      'zikr_name_ar': 'Arapça İsim',
      'zikr_name_tr': 'Türkçe İsim',
      'zikr_name_en': 'İngilizce İsim',
      'default_count': 'Varsayılan Adet',
      'set_target': 'Hedef Belirle',
      'quick_select': 'Hızlı Seçim',
      'custom_target': 'Özel Hedef',
      'enter_target': 'Hedef sayısını girin',
      'success_title': 'Maşallah! 🎉',
      'success_message': 'Hedefinize ulaştınız!',
      'zikr_count': 'Zikir',
      'edit': 'Düzenle',
      'delete': 'Sil',
      'save': 'Kaydet',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Sayacı artır',
      'resetCounter': 'Sayacı sıfırla',
      'changeTarget': 'Hedefi değiştir',
      'vibrationOn': 'Titreşim açık',
      'vibrationOff': 'Titreşim kapalı',
      'soundOn': 'Ses açık',
      'soundOff': 'Ses kapalı',
      'about': 'Hakkında',
      'confettiOn': 'Konfeti açık',
      'confettiOff': 'Konfeti kapalı',
      'setReminder': 'Hatırlatıcı Ayarla',
      'cancelReminder': 'İptal Et',
      'goals': 'Hedefler',
      'dailyGoal': 'Günlük Hedef',
      'weeklyGoal': 'Haftalık Hedef',
      'monthlyGoal': 'Aylık Hedef',
      'setGoal': 'Hedef Belirle',
      'goalCompleted': 'Hedef Tamamlandı! 🎯',
      'progress': 'İlerleme',
    },
    'en': {
      'app_name': 'Tasbih Counter',
      'counter': 'Counter',
      'target': 'Target',
      'reset': 'Reset',
      'continue': 'Continue',
      'cancel': 'Cancel',
      'ok': 'OK',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'vibration': 'Vibration',
      'sound': 'Sound',
      'select_zikr': 'Select Dhikr',
      'add_zikr': 'Add Dhikr',
      'custom_zikrs': 'Custom Dhikrs',
      'zikr_name_ar': 'Arabic Name',
      'zikr_name_tr': 'Turkish Name',
      'zikr_name_en': 'English Name',
      'default_count': 'Default Count',
      'set_target': 'Set Target',
      'quick_select': 'Quick Select',
      'custom_target': 'Custom Target',
      'enter_target': 'Enter target number',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Target reached!',
      'zikr_count': 'Dhikr',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Increment counter',
      'resetCounter': 'Reset counter',
      'changeTarget': 'Change target',
      'vibrationOn': 'Vibration on',
      'vibrationOff': 'Vibration off',
      'soundOn': 'Sound on',
      'soundOff': 'Sound off',
      'about': 'About',
      'confettiOn': 'Confetti on',
      'confettiOff': 'Confetti off',
      'setReminder': 'Set Reminder',
      'cancelReminder': 'Cancel',
      'goals': 'Goals',
      'dailyGoal': 'Daily Goal',
      'weeklyGoal': 'Weekly Goal',
      'monthlyGoal': 'Monthly Goal',
      'setGoal': 'Set Goal',
      'goalCompleted': 'Goal Completed! 🎯',
      'progress': 'Progress',
    },
    'ar': {
      'app_name': 'مسبحة إلكترونية',
      'counter': 'العداد',
      'target': 'الهدف',
      'reset': 'إعادة تعيين',
      'continue': 'متابعة',
      'cancel': 'إلغاء',
      'ok': 'موافق',
      'settings': 'الإعدادات',
      'theme': 'المظهر',
      'language': 'اللغة',
      'vibration': 'الاهتزاز',
      'sound': 'الصوت',
      'select_zikr': 'اختر الذكر',
      'add_zikr': 'إضافة ذكر',
      'custom_zikrs': 'أذكار مخصصة',
      'zikr_name_ar': 'الاسم بالعربية',
      'zikr_name_tr': 'الاسم بالتركية',
      'zikr_name_en': 'الاسم بالإنجليزية',
      'default_count': 'العدد الافتراضي',
      'set_target': 'تحديد الهدف',
      'quick_select': 'اختيار سريع',
      'custom_target': 'هدف مخصص',
      'enter_target': 'أدخل رقم الهدف',
      'success_title': 'ماشاء الله! 🎉',
      'success_message': 'تم الوصول إلى الهدف!',
      'zikr_count': 'ذكر',
      'edit': 'تعديل',
      'delete': 'حذف',
      'save': 'حفظ',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'زيادة العداد',
      'resetCounter': 'إعادة ضبط العداد',
      'changeTarget': 'تغيير الهدف',
      'vibrationOn': 'الاهتزاز قيد التشغيل',
      'vibrationOff': 'الاهتزاز متوقف',
      'soundOn': 'الصوت قيد التشغيل',
      'soundOff': 'الصوت مغلق',
      'about': 'حول',
      'confettiOn': 'الاحتفال مفعل',
      'confettiOff': 'الاحتفال معطل',
      'setReminder': 'تعيين تذكير',
      'cancelReminder': 'إلغاء',
      'goals': 'الأهداف',
      'dailyGoal': 'الهدف اليومي',
      'weeklyGoal': 'الهدف الأسبوعي',
      'monthlyGoal': 'الهدف الشهري',
      'setGoal': 'تحديد الهدف',
      'goalCompleted': 'تم إنجاز الهدف! 🎯',
      'progress': 'التقدم',
    },
    'id': {
      'app_name': 'Tasbih Digital',
      'counter': 'Penghitung',
      'target': 'Target',
      'reset': 'Atur Ulang',
      'continue': 'Lanjutkan',
      'cancel': 'Batal',
      'ok': 'OK',
      'settings': 'Pengaturan',
      'theme': 'Tema',
      'language': 'Bahasa',
      'vibration': 'Getaran',
      'sound': 'Suara',
      'select_zikr': 'Pilih Dzikir',
      'add_zikr': 'Tambah Dzikir',
      'custom_zikrs': 'Dzikir Kustom',
      'zikr_name_ar': 'Nama Arab',
      'zikr_name_tr': 'Nama Turki',
      'zikr_name_en': 'Nama Inggris',
      'default_count': 'Jumlah Default',
      'set_target': 'Atur Target',
      'quick_select': 'Pilihan Cepat',
      'custom_target': 'Target Kustom',
      'enter_target': 'Masukkan nomor target',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Target tercapai!',
      'zikr_count': 'Dzikir',
      'edit': 'Edit',
      'delete': 'Hapus',
      'save': 'Simpan',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Tambah penghitung',
      'resetCounter': 'Atur ulang penghitung',
      'changeTarget': 'Ubah target',
      'vibrationOn': 'Getaran aktif',
      'vibrationOff': 'Getaran nonaktif',
      'soundOn': 'Suara aktif',
      'soundOff': 'Suara nonaktif',
      'about': 'Tentang',
      'confettiOn': 'Konfeti aktif',
      'confettiOff': 'Konfeti nonaktif',
      'setReminder': 'Atur Pengingat',
      'cancelReminder': 'Batal',
      'goals': 'Target',
      'dailyGoal': 'Target Harian',
      'weeklyGoal': 'Target Mingguan',
      'monthlyGoal': 'Target Bulanan',
      'setGoal': 'Atur Target',
      'goalCompleted': 'Target Tercapai! 🎯',
      'progress': 'Kemajuan',
    },
    // Urduca (Pakistan, Hindistan)
    'ur': {
      'app_name': 'تسبیح کاؤنٹر',
      'counter': 'کاؤنٹر',
      'target': 'ہدف',
      'reset': 'ریسیٹ',
      'continue': 'جاری رکھیں',
      'cancel': 'منسوخ',
      'ok': 'ٹھیک ہے',
      'settings': 'ترتیبات',
      'theme': 'تھیم',
      'language': 'زبان',
      'vibration': 'تھرتھراہٹ',
      'sound': 'آواز',
      'success_title': 'ماشاء اللہ! 🎉',
      'success_message': 'ہدف حاصل!',
      'goals': 'اہداف',
      'dailyGoal': 'روزانہ ہدف',
      'weeklyGoal': 'ہفتہ وار ہدف',
      'monthlyGoal': 'ماہانہ ہدف',
      'progress': 'پیش رفت',
    },
    // Bengalce (Bangladeş)
    'bn': {
      'app_name': 'তসবিহ কাউন্টার',
      'counter': 'কাউন্টার',
      'target': 'লক্ষ্য',
      'reset': 'রিসেট',
      'continue': 'চালিয়ে যান',
      'cancel': 'বাতিল',
      'ok': 'ঠিক আছে',
      'settings': 'সেটিংস',
      'theme': 'থিম',
      'language': 'ভাষা',
      'vibration': 'কম্পন',
      'sound': 'শব্দ',
      'success_title': 'মাশাআল্লাহ! 🎉',
      'success_message': 'লক্ষ্য পৌঁছেছে!',
      'goals': 'লক্ষ্য',
      'dailyGoal': 'দৈনিক লক্ষ্য',
      'weeklyGoal': 'সাপ্তাহিক লক্ষ্য',
      'monthlyGoal': 'মাসিক লক্ষ্য',
      'progress': 'অগ্রগতি',
    },
    // Malayca (Malezya)
    'ms': {
      'app_name': 'Kaunter Tasbih',
      'counter': 'Kaunter',
      'target': 'Sasaran',
      'reset': 'Set Semula',
      'continue': 'Teruskan',
      'cancel': 'Batal',
      'ok': 'OK',
      'settings': 'Tetapan',
      'theme': 'Tema',
      'language': 'Bahasa',
      'vibration': 'Getaran',
      'sound': 'Bunyi',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Sasaran tercapai!',
      'goals': 'Matlamat',
      'dailyGoal': 'Matlamat Harian',
      'weeklyGoal': 'Matlamat Mingguan',
      'monthlyGoal': 'Matlamat Bulanan',
      'progress': 'Kemajuan',
    },
    // Farsça (İran)
    'fa': {
      'app_name': 'شمارنده تسبیح',
      'counter': 'شمارنده',
      'target': 'هدف',
      'reset': 'بازنشانی',
      'continue': 'ادامه',
      'cancel': 'لغو',
      'ok': 'تأیید',
      'settings': 'تنظیمات',
      'theme': 'تم',
      'language': 'زبان',
      'vibration': 'لرزش',
      'sound': 'صدا',
      'success_title': 'ماشاءالله! 🎉',
      'success_message': 'به هدف رسیدید!',
      'goals': 'اهداف',
      'dailyGoal': 'هدف روزانه',
      'weeklyGoal': 'هدف هفتگی',
      'monthlyGoal': 'هدف ماهانه',
      'progress': 'پیشرفت',
    },
    // Fransızca (Kuzey Afrika)
    'fr': {
      'app_name': 'Compteur Tasbih',
      'counter': 'Compteur',
      'target': 'Objectif',
      'reset': 'Réinitialiser',
      'continue': 'Continuer',
      'cancel': 'Annuler',
      'ok': 'OK',
      'settings': 'Paramètres',
      'theme': 'Thème',
      'language': 'Langue',
      'vibration': 'Vibration',
      'sound': 'Son',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Objectif atteint!',
      'goals': 'Objectifs',
      'dailyGoal': 'Objectif Quotidien',
      'weeklyGoal': 'Objectif Hebdomadaire',
      'monthlyGoal': 'Objectif Mensuel',
      'progress': 'Progrès',
    },
    // Çince (Çin)
    'zh': {
      'app_name': '计数器',
      'counter': '计数器',
      'target': '目标',
      'reset': '重置',
      'continue': '继续',
      'cancel': '取消',
      'ok': '确定',
      'settings': '设置',
      'theme': '主题',
      'language': '语言',
      'vibration': '震动',
      'sound': '声音',
      'success_title': '太棒了! 🎉',
      'success_message': '目标达成!',
      'goals': '目标',
      'dailyGoal': '每日目标',
      'weeklyGoal': '每周目标',
      'monthlyGoal': '每月目标',
      'progress': '进度',
    },
    // Japonca (Japonya)
    'ja': {
      'app_name': 'カウンター',
      'counter': 'カウンター',
      'target': '目標',
      'reset': 'リセット',
      'continue': '続ける',
      'cancel': 'キャンセル',
      'ok': 'OK',
      'settings': '設定',
      'theme': 'テーマ',
      'language': '言語',
      'vibration': '振動',
      'sound': '音',
      'success_title': '素晴らしい! 🎉',
      'success_message': '目標達成!',
      'goals': '目標',
      'dailyGoal': '毎日の目標',
      'weeklyGoal': '毎週の目標',
      'monthlyGoal': '毎月の目標',
      'progress': '進捗',
    },
    // Rusça (Rusya)
    'ru': {
      'app_name': 'Счётчик',
      'counter': 'Счётчик',
      'target': 'Цель',
      'reset': 'Сброс',
      'continue': 'Продолжить',
      'cancel': 'Отмена',
      'ok': 'OK',
      'settings': 'Настройки',
      'theme': 'Тема',
      'language': 'Язык',
      'vibration': 'Вибрация',
      'sound': 'Звук',
      'success_title': 'Отлично! 🎉',
      'success_message': 'Цель достигнута!',
      'goals': 'Цели',
      'dailyGoal': 'Ежедневная цель',
      'weeklyGoal': 'Еженедельная цель',
      'monthlyGoal': 'Ежемесячная цель',
      'progress': 'Прогресс',
    },
    // Almanca (Almanya)
    'de': {
      'app_name': 'Zähler',
      'counter': 'Zähler',
      'target': 'Ziel',
      'reset': 'Zurücksetzen',
      'continue': 'Weiter',
      'cancel': 'Abbrechen',
      'ok': 'OK',
      'settings': 'Einstellungen',
      'theme': 'Thema',
      'language': 'Sprache',
      'vibration': 'Vibration',
      'sound': 'Ton',
      'success_title': 'Ausgezeichnet! 🎉',
      'success_message': 'Ziel erreicht!',
      'goals': 'Ziele',
      'dailyGoal': 'Tägliches Ziel',
      'weeklyGoal': 'Wöchentliches Ziel',
      'monthlyGoal': 'Monatliches Ziel',
      'progress': 'Fortschritt',
    },
    // Svahili (Doğu Afrika)
    'sw': {
      'app_name': 'Kihesabu',
      'counter': 'Kihesabu',
      'target': 'Lengo',
      'reset': 'Weka Upya',
      'continue': 'Endelea',
      'cancel': 'Ghairi',
      'ok': 'Sawa',
      'settings': 'Mipangilio',
      'theme': 'Mandhari',
      'language': 'Lugha',
      'vibration': 'Mtetemo',
      'sound': 'Sauti',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Lengo limefikiwa!',
      'goals': 'Malengo',
      'dailyGoal': 'Lengo la Kila Siku',
      'weeklyGoal': 'Lengo la Kila Wiki',
      'monthlyGoal': 'Lengo la Kila Mwezi',
      'progress': 'Maendeleo',
    },
    // Hausa (Batı Afrika)
    'ha': {
      'app_name': 'Mai Ƙidaya',
      'counter': 'Mai Ƙidaya',
      'target': 'Manufa',
      'reset': 'Sake Saita',
      'continue': 'Ci gaba',
      'cancel': 'Soke',
      'ok': 'To',
      'settings': 'Saitunan',
      'theme': 'Jigo',
      'language': 'Harshe',
      'vibration': 'Girgiza',
      'sound': 'Sauti',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'An cimma manufa!',
      'goals': 'Manufofi',
      'dailyGoal': 'Manufar Yau da Kullum',
      'weeklyGoal': 'Manufar Mako-mako',
      'monthlyGoal': 'Manufar Wata-wata',
      'progress': 'Ci gaba',
    },
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }

  String get appName => translate('app_name');
  String get counter => translate('counter');
  String get target => translate('target');
  String get reset => translate('reset');
  String get continueText => translate('continue');
  String get cancel => translate('cancel');
  String get ok => translate('ok');
  String get settings => translate('settings');
  String get theme => translate('theme');
  String get language => translate('language');
  String get vibration => translate('vibration');
  String get sound => translate('sound');
  String get selectZikr => translate('select_zikr');
  String get addZikr => translate('add_zikr');
  String get customZikrs => translate('custom_zikrs');
  String get zikrNameAr => translate('zikr_name_ar');
  String get zikrNameTr => translate('zikr_name_tr');
  String get zikrNameEn => translate('zikr_name_en');
  String get defaultCount => translate('default_count');
  String get setTarget => translate('set_target');
  String get quickSelect => translate('quick_select');
  String get customTarget => translate('custom_target');
  String get enterTarget => translate('enter_target');
  String get successTitle => translate('success_title');
  String get successMessage => translate('success_message');
  String get zikrCount => translate('zikr_count');
  String get edit => translate('edit');
  String get delete => translate('delete');
  String get save => translate('save');
  String get arabic => translate('arabic');
  String get turkish => translate('turkish');
  String get english => translate('english');
  String get indonesian => translate('indonesian');
  String get incrementCounter => translate('incrementCounter');
  String get resetCounter => translate('resetCounter');
  String get changeTarget => translate('changeTarget');
  String get vibrationOn => translate('vibrationOn');
  String get vibrationOff => translate('vibrationOff');
  String get soundOn => translate('soundOn');
  String get soundOff => translate('soundOff');
  String get about => translate('about');
  String get confettiOn => translate('confettiOn');
  String get confettiOff => translate('confettiOff');
  String get setReminder => translate('setReminder');
  String get cancelReminder => translate('cancelReminder');
  String get goals => translate('goals');
  String get dailyGoal => translate('dailyGoal');
  String get weeklyGoal => translate('weeklyGoal');
  String get monthlyGoal => translate('monthlyGoal');
  String get setGoal => translate('setGoal');
  String get goalCompleted => translate('goalCompleted');
  String get progress => translate('progress');
}
