class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_name': 'Zikirmatik',
      'counter': 'Sayaç',
      'target': 'Hedef',
      'reset': 'Sıfırla',
      'continue': 'Devam Et',
      'cancel': 'İptal',
      'ok': 'Tamam',
      'settings': 'Ayarlar',
      'theme': 'Tema',
      'language': 'Dil',
      'vibration': 'Titreşim',
      'sound': 'Ses',
      'select_zikr': 'Zikir Seç',
      'add_zikr': 'Zikir Ekle',
      'custom_zikrs': 'Özel Zikirler',
      'zikr_name_ar': 'Arapça İsim',
      'zikr_name_tr': 'Türkçe İsim',
      'zikr_name_en': 'İngilizce İsim',
      'zikr_name_id': 'İndonezce İsim',
      'zikr_name_ur': 'Urduca İsim',
      'zikr_name_bn': 'Bengalce İsim',
      'zikr_name_ms': 'Malayca İsim',
      'zikr_name_fa': 'Farsça İsim',
      'zikr_name_fr': 'Fransızca İsim',
      'zikr_name_zh': 'Çince İsim',
      'zikr_name_ja': 'Japonca İsim',
      'zikr_name_ru': 'Rusça İsim',
      'zikr_name_de': 'Almanca İsim',
      'zikr_name_sw': 'Svahili İsim',
      'zikr_name_ha': 'Hausa İsim',
      'contact': 'İletişim',
      'source_code': 'Kaynak Kodu',
      'default_count': 'Varsayılan Adet',
      'set_target': 'Hedef Belirle',
      'quick_select': 'Hızlı Seçim',
      'custom_target': 'Özel Hedef',
      'enter_target': 'Hedef sayısını girin',
      'success_title': 'Maşallah! 🎉',
      'success_message': 'Hedefinize ulaştınız!',
      'zikr_count': 'Zikir',
      'edit': 'Düzenle',
      'delete': 'Sil',
      'save': 'Kaydet',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Sayacı artır',
      'resetCounter': 'Sayacı sıfırla',
      'changeTarget': 'Hedefi değiştir',
      'vibrationOn': 'Titreşim açık',
      'vibrationOff': 'Titreşim kapalı',
      'soundOn': 'Ses açık',
      'soundOff': 'Ses kapalı',
      'about': 'Hakkında',
      'confettiOn': 'Konfeti açık',
      'confettiOff': 'Konfeti kapalı',
      'setReminder': 'Hatırlatıcı Ayarla',
      'cancelReminder': 'İptal Et',
      'goals': 'Hedefler',
      'dailyGoal': 'Günlük Hedef',
      'weeklyGoal': 'Haftalık Hedef',
      'monthlyGoal': 'Aylık Hedef',
      'setGoal': 'Hedef Belirle',
      'goalCompleted': 'Hedef Tamamlandı! 🎯',
      'progress': 'İlerleme',
      'statistics': 'İstatistikler',
      'today': 'Bugün',
      'total': 'Toplam',
      'streak': 'Seri',
      'consecutiveDays': 'Ardışık günler',
      'last7Days': 'Son 7 Gün',
      'days': 'gün',
      'mon': 'Pzt',
      'tue': 'Sal',
      'wed': 'Çar',
      'thu': 'Per',
      'fri': 'Cum',
      'sat': 'Cmt',
      'sun': 'Paz',
      'trophies': 'Kupalar',
      'streak_continues': 'çizgi devam ediyor',
      'new_record': 'Yeni rekor!',
      'achievement_streaks': 'Başarı Çizgileri',
      'weeks': 'Hafta',
      'months': 'Ay',
      'last_4_weeks': 'Son 4 Hafta',
      'last_12_months': 'Son 12 Ay',
      'optional': 'Opsiyonel',
      'required': 'gerekli',
      'transliteration': 'Okunuş',
      'version': 'Sürüm 1.0.0',
      'support_us': 'Bizi Destekleyin',
      'support_description': 'Kısa bir reklam izleyerek bu uygulamayı ücretsiz tutmamıza yardımcı olun. Desteğiniz bizim için çok değerli!',
      'watch_ad': 'Reklam İzle',
      'ad_not_ready': 'Reklam hazır değil, lütfen tekrar deneyin',
      'thank_you_support': 'Desteğiniz için teşekkür ederiz! 🙏',
      'features': 'Özellikler',
      'feature_goals': 'Günlük, Haftalık, Aylık Hedefler',
      'feature_statistics': 'Detaylı İstatistikler',
      'feature_widget': 'Ana Ekran Widget',
      'feature_languages': '15 Dil Desteği',
      'day_streak': 'Günlük Seri',
      'new_best': 'Yeni Rekor!',
      'completed_today': 'Bugün Tamamlanan',
      'tts': 'Sesli Okuma',
      'ttsOn': 'Sesli okuma açık',
      'ttsOff': 'Sesli okuma kapalı',
      'speak_zikr': 'Zikri Oku',
    },
    'en': {
      'app_name': 'Tasbih Counter',
      'counter': 'Counter',
      'target': 'Target',
      'reset': 'Reset',
      'continue': 'Continue',
      'cancel': 'Cancel',
      'ok': 'OK',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'vibration': 'Vibration',
      'sound': 'Sound',
      'select_zikr': 'Select Dhikr',
      'add_zikr': 'Add Dhikr',
      'custom_zikrs': 'Custom Dhikrs',
      'zikr_name_ar': 'Arabic Name',
      'zikr_name_tr': 'Turkish Name',
      'zikr_name_en': 'English Name',
      'zikr_name_id': 'Indonesian Name',
      'zikr_name_ur': 'Urdu Name',
      'zikr_name_bn': 'Bengali Name',
      'zikr_name_ms': 'Malay Name',
      'zikr_name_fa': 'Persian Name',
      'zikr_name_fr': 'French Name',
      'zikr_name_zh': 'Chinese Name',
      'zikr_name_ja': 'Japanese Name',
      'zikr_name_ru': 'Russian Name',
      'zikr_name_de': 'German Name',
      'zikr_name_sw': 'Swahili Name',
      'zikr_name_ha': 'Hausa Name',
      'contact': 'Contact',
      'source_code': 'Source Code',
      'default_count': 'Default Count',
      'set_target': 'Set Target',
      'quick_select': 'Quick Select',
      'custom_target': 'Custom Target',
      'enter_target': 'Enter target number',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Target reached!',
      'zikr_count': 'Dhikr',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Increment counter',
      'resetCounter': 'Reset counter',
      'changeTarget': 'Change target',
      'vibrationOn': 'Vibration on',
      'vibrationOff': 'Vibration off',
      'soundOn': 'Sound on',
      'soundOff': 'Sound off',
      'about': 'About',
      'confettiOn': 'Confetti on',
      'confettiOff': 'Confetti off',
      'setReminder': 'Set Reminder',
      'cancelReminder': 'Cancel',
      'goals': 'Goals',
      'dailyGoal': 'Daily Goal',
      'weeklyGoal': 'Weekly Goal',
      'monthlyGoal': 'Monthly Goal',
      'setGoal': 'Set Goal',
      'goalCompleted': 'Goal Completed! 🎯',
      'progress': 'Progress',
      'statistics': 'Statistics',
      'today': 'Today',
      'total': 'Total',
      'streak': 'Streak',
      'consecutiveDays': 'Consecutive days',
      'last7Days': 'Last 7 Days',
      'days': 'days',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'trophies': 'Trophies',
      'streak_continues': 'streak continues',
      'new_record': 'New record!',
      'achievement_streaks': 'Achievement Streaks',
      'weeks': 'Weeks',
      'months': 'Months',
      'last_4_weeks': 'Last 4 Weeks',
      'last_12_months': 'Last 12 Months',
      'optional': 'Optional',
      'required': 'required',
      'transliteration': 'Transliteration',
      'version': 'Version 1.0.0',
      'support_us': 'Support Us',
      'support_description': 'Help us keep this app free by watching a short ad. Your support means a lot!',
      'watch_ad': 'Watch Ad',
      'ad_not_ready': 'Ad not ready, please try again',
      'thank_you_support': 'Thank you for your support! 🙏',
      'features': 'Features',
      'feature_goals': 'Daily, Weekly, Monthly Goals',
      'feature_statistics': 'Detailed Statistics',
      'feature_widget': 'Home Screen Widget',
      'feature_languages': '15 Languages Support',
      'day_streak': 'Day Streak',
      'new_best': 'New Best!',
      'completed_today': 'Completed Today',
      'tts': 'Voice Reading',
      'ttsOn': 'Voice reading on',
      'ttsOff': 'Voice reading off',
      'speak_zikr': 'Speak Dhikr',
    },
    'ar': {
      'app_name': 'مسبحة إلكترونية',
      'counter': 'العداد',
      'target': 'الهدف',
      'reset': 'إعادة تعيين',
      'continue': 'متابعة',
      'cancel': 'إلغاء',
      'ok': 'موافق',
      'settings': 'الإعدادات',
      'theme': 'المظهر',
      'language': 'اللغة',
      'vibration': 'الاهتزاز',
      'sound': 'الصوت',
      'select_zikr': 'اختر الذكر',
      'add_zikr': 'إضافة ذكر',
      'custom_zikrs': 'أذكار مخصصة',
      'zikr_name_ar': 'الاسم بالعربية',
      'zikr_name_tr': 'الاسم بالتركية',
      'zikr_name_en': 'الاسم بالإنجليزية',
      'zikr_name_id': 'الاسم بالإندونيسية',
      'zikr_name_ur': 'الاسم بالأردية',
      'zikr_name_bn': 'الاسم بالبنغالية',
      'zikr_name_ms': 'الاسم بالملايو',
      'zikr_name_fa': 'الاسم بالفارسية',
      'zikr_name_fr': 'الاسم بالفرنسية',
      'zikr_name_zh': 'الاسم بالصينية',
      'zikr_name_ja': 'الاسم باليابانية',
      'zikr_name_ru': 'الاسم بالروسية',
      'zikr_name_de': 'الاسم بالألمانية',
      'zikr_name_sw': 'الاسم بالسواحيلية',
      'zikr_name_ha': 'الاسم بالهوسا',
      'contact': 'اتصل',
      'source_code': 'الكود المصدري',
      'default_count': 'العدد الافتراضي',
      'set_target': 'تحديد الهدف',
      'quick_select': 'اختيار سريع',
      'custom_target': 'هدف مخصص',
      'enter_target': 'أدخل رقم الهدف',
      'success_title': 'ماشاء الله! 🎉',
      'success_message': 'تم الوصول إلى الهدف!',
      'zikr_count': 'ذكر',
      'edit': 'تعديل',
      'delete': 'حذف',
      'save': 'حفظ',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'زيادة العداد',
      'resetCounter': 'إعادة ضبط العداد',
      'changeTarget': 'تغيير الهدف',
      'vibrationOn': 'الاهتزاز قيد التشغيل',
      'vibrationOff': 'الاهتزاز متوقف',
      'soundOn': 'الصوت قيد التشغيل',
      'soundOff': 'الصوت مغلق',
      'about': 'حول',
      'confettiOn': 'الاحتفال مفعل',
      'confettiOff': 'الاحتفال معطل',
      'setReminder': 'تعيين تذكير',
      'cancelReminder': 'إلغاء',
      'goals': 'الأهداف',
      'dailyGoal': 'الهدف اليومي',
      'weeklyGoal': 'الهدف الأسبوعي',
      'monthlyGoal': 'الهدف الشهري',
      'setGoal': 'تحديد الهدف',
      'goalCompleted': 'تم إنجاز الهدف! 🎯',
      'progress': 'التقدم',
      'statistics': 'الإحصائيات',
      'today': 'اليوم',
      'total': 'المجموع',
      'streak': 'السلسلة',
      'consecutiveDays': 'أيام متتالية',
      'last7Days': 'آخر 7 أيام',
      'days': 'أيام',
      'mon': 'الإثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'fri': 'الجمعة',
      'sat': 'السبت',
      'sun': 'الأحد',
      'trophies': 'الجوائز',
      'streak_continues': 'السلسلة مستمرة',
      'new_record': 'رقم قياسي جديد!',
      'achievement_streaks': 'سلاسل الإنجاز',
      'weeks': 'أسابيع',
      'months': 'أشهر',
      'last_4_weeks': 'آخر 4 أسابيع',
      'last_12_months': 'آخر 12 شهر',
      'optional': 'اختياري',
      'required': 'مطلوب',
      'transliteration': 'النطق',
      'version': 'الإصدار 1.0.0',
      'support_us': 'ادعمنا',
      'support_description': 'ساعدنا في الحفاظ على هذا التطبيق مجانيًا من خلال مشاهدة إعلان قصير. دعمك يعني الكثير!',
      'watch_ad': 'شاهد الإعلان',
      'ad_not_ready': 'الإعلان غير جاهز، يرجى المحاولة مرة أخرى',
      'thank_you_support': 'شكرا لدعمك! 🙏',
      'features': 'الميزات',
      'feature_goals': 'أهداف يومية وأسبوعية وشهرية',
      'feature_statistics': 'إحصائيات مفصلة',
      'feature_widget': 'ويدجت الشاشة الرئيسية',
      'feature_languages': 'دعم 15 لغة',
      'day_streak': 'سلسلة يومية',
      'new_best': 'أفضل جديد!',
      'completed_today': 'مكتمل اليوم',
      'tts': 'القراءة الصوتية',
      'ttsOn': 'القراءة الصوتية قيد التشغيل',
      'ttsOff': 'القراءة الصوتية متوقفة',
      'speak_zikr': 'اقرأ الذكر',
    },
    'id': {
      'app_name': 'Tasbih Digital',
      'counter': 'Penghitung',
      'target': 'Target',
      'reset': 'Atur Ulang',
      'continue': 'Lanjutkan',
      'cancel': 'Batal',
      'ok': 'OK',
      'settings': 'Pengaturan',
      'theme': 'Tema',
      'language': 'Bahasa',
      'vibration': 'Getaran',
      'sound': 'Suara',
      'select_zikr': 'Pilih Dzikir',
      'add_zikr': 'Tambah Dzikir',
      'custom_zikrs': 'Dzikir Kustom',
      'zikr_name_ar': 'Nama Arab',
      'zikr_name_tr': 'Nama Turki',
      'zikr_name_en': 'Nama Inggris',
      'zikr_name_id': 'Nama Indonesia',
      'zikr_name_ur': 'Nama Urdu',
      'zikr_name_bn': 'Nama Bengali',
      'zikr_name_ms': 'Nama Melayu',
      'zikr_name_fa': 'Nama Persia',
      'zikr_name_fr': 'Nama Prancis',
      'zikr_name_zh': 'Nama Cina',
      'zikr_name_ja': 'Nama Jepang',
      'zikr_name_ru': 'Nama Rusia',
      'zikr_name_de': 'Nama Jerman',
      'zikr_name_sw': 'Nama Swahili',
      'zikr_name_ha': 'Nama Hausa',
      'contact': 'Hubungi',
      'source_code': 'Kode Sumber',
      'default_count': 'Jumlah Default',
      'set_target': 'Atur Target',
      'quick_select': 'Pilihan Cepat',
      'custom_target': 'Target Kustom',
      'enter_target': 'Masukkan nomor target',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Target tercapai!',
      'zikr_count': 'Dzikir',
      'edit': 'Edit',
      'delete': 'Hapus',
      'save': 'Simpan',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Tambah penghitung',
      'resetCounter': 'Atur ulang penghitung',
      'changeTarget': 'Ubah target',
      'vibrationOn': 'Getaran aktif',
      'vibrationOff': 'Getaran nonaktif',
      'soundOn': 'Suara aktif',
      'soundOff': 'Suara nonaktif',
      'about': 'Tentang',
      'confettiOn': 'Konfeti aktif',
      'confettiOff': 'Konfeti nonaktif',
      'setReminder': 'Atur Pengingat',
      'cancelReminder': 'Batal',
      'goals': 'Target',
      'dailyGoal': 'Target Harian',
      'weeklyGoal': 'Target Mingguan',
      'monthlyGoal': 'Target Bulanan',
      'setGoal': 'Atur Target',
      'goalCompleted': 'Target Tercapai! 🎯',
      'progress': 'Kemajuan',
      'statistics': 'Statistik',
      'today': 'Hari Ini',
      'total': 'Total',
      'streak': 'Beruntun',
      'consecutiveDays': 'Hari berturut-turut',
      'last7Days': '7 Hari Terakhir',
      'days': 'hari',
      'mon': 'Sen',
      'tue': 'Sel',
      'wed': 'Rab',
      'thu': 'Kam',
      'fri': 'Jum',
      'sat': 'Sab',
      'sun': 'Min',
      'trophies': 'Trofi',
      'streak_continues': 'beruntun berlanjut',
      'new_record': 'Rekor baru!',
      'achievement_streaks': 'Pencapaian Beruntun',
      'weeks': 'Minggu',
      'months': 'Bulan',
      'last_4_weeks': '4 Minggu Terakhir',
      'last_12_months': '12 Bulan Terakhir',
      'optional': 'Opsional',
      'required': 'diperlukan',
      'transliteration': 'Transliterasi',
      'version': 'Versi 1.0.0',
      'support_us': 'Dukung Kami',
      'support_description': 'Bantu kami menjaga aplikasi ini gratis dengan menonton iklan singkat. Dukungan Anda sangat berarti!',
      'watch_ad': 'Tonton Iklan',
      'ad_not_ready': 'Iklan belum siap, silakan coba lagi',
      'thank_you_support': 'Terima kasih atas dukungan Anda! 🙏',
      'features': 'Fitur',
      'feature_goals': 'Target Harian, Mingguan, Bulanan',
      'feature_statistics': 'Statistik Terperinci',
      'feature_widget': 'Widget Layar Utama',
      'feature_languages': 'Dukungan 15 Bahasa',
      'day_streak': 'Beruntun Harian',
      'new_best': 'Terbaik Baru!',
      'completed_today': 'Selesai Hari Ini',
      'tts': 'Pembacaan Suara',
      'ttsOn': 'Pembacaan suara aktif',
      'ttsOff': 'Pembacaan suara nonaktif',
      'speak_zikr': 'Bacakan Dzikir',
    },
    // Urduca (Pakistan, Hindistan)
    'ur': {
      'app_name': 'تسبیح کاؤنٹر',
      'counter': 'کاؤنٹر',
      'target': 'ہدف',
      'reset': 'ریسیٹ',
      'continue': 'جاری رکھیں',
      'cancel': 'منسوخ',
      'ok': 'ٹھیک ہے',
      'settings': 'ترتیبات',
      'theme': 'تھیم',
      'language': 'زبان',
      'vibration': 'تھرتھراہٹ',
      'sound': 'آواز',
      'success_title': 'ماشاء اللہ! 🎉',
      'success_message': 'ہدف حاصل!',
      'goals': 'اہداف',
      'dailyGoal': 'روزانہ ہدف',
      'weeklyGoal': 'ہفتہ وار ہدف',
      'monthlyGoal': 'ماہانہ ہدف',
      'progress': 'پیش رفت',
      'statistics': 'شماریات',
      'today': 'آج',
      'total': 'کل',
      'streak': 'سلسلہ',
      'consecutiveDays': 'مسلسل دن',
      'last7Days': 'آخری 7 دن',
      'days': 'دن',
      'select_zikr': 'ذکر منتخب کریں',
      'add_zikr': 'ذکر شامل کریں',
      'custom_zikrs': 'حسب ضرورت ذکر',
      'zikr_name_ar': 'عربی نام',
      'zikr_name_tr': 'ترکی نام',
      'zikr_name_en': 'انگریزی نام',
      'zikr_name_id': 'انڈونیشیائی نام',
      'zikr_name_ur': 'اردو نام',
      'zikr_name_bn': 'بنگالی نام',
      'zikr_name_ms': 'ملائی نام',
      'zikr_name_fa': 'فارسی نام',
      'zikr_name_fr': 'فرانسیسی نام',
      'zikr_name_zh': 'چینی نام',
      'zikr_name_ja': 'جاپانی نام',
      'zikr_name_ru': 'روسی نام',
      'zikr_name_de': 'جرمن نام',
      'zikr_name_sw': 'سواحیلی نام',
      'zikr_name_ha': 'ہاؤسا نام',
      'default_count': 'ڈیفالٹ تعداد',
      'set_target': 'ہدف مقرر کریں',
      'quick_select': 'فوری انتخاب',
      'custom_target': 'حسب ضرورت ہدف',
      'enter_target': 'ہدف نمبر درج کریں',
      'setGoal': 'ہدف مقرر کریں',
      'goalCompleted': 'ہدف مکمل! 🎯',
      'zikr_count': 'ذکر',
      'edit': 'ترمیم',
      'delete': 'حذف کریں',
      'save': 'محفوظ کریں',
      'trophies': 'انعامات',
      'streak_continues': 'سلسلہ جاری',
      'new_record': 'نیا ریکارڈ!',
      'achievement_streaks': 'کامیابی کے سلسلے',
      'weeks': 'ہفتے',
      'months': 'مہینے',
      'last_4_weeks': 'آخری 4 ہفتے',
      'last_12_months': 'آخری 12 مہینے',
      'optional': 'اختیاری',
      'required': 'ضروری',
      'transliteration': 'نقل حرفی',
      'version': 'ورژن 1.0.0',
      'support_us': 'ہماری مدد کریں',
      'support_description': 'ایک مختصر اشتہار دیکھ کر اس ایپ کو مفت رکھنے میں ہماری مدد کریں۔ آپ کی حمایت بہت اہمیت رکھتی ہے!',
      'watch_ad': 'اشتہار دیکھیں',
      'ad_not_ready': 'اشتہار تیار نہیں، براہ کرم دوبارہ کوشش کریں',
      'thank_you_support': 'آپ کی حمایت کا شکریہ! 🙏',
      'features': 'خصوصیات',
      'feature_goals': 'روزانہ، ہفتہ وار، ماہانہ اہداف',
      'feature_statistics': 'تفصیلی شماریات',
      'feature_widget': 'ہوم اسکرین ویجٹ',
      'feature_languages': '15 زبانوں کی معاونت',
    },
    // Bengalce (Bangladeş)
    'bn': {
      'app_name': 'তসবিহ কাউন্টার',
      'counter': 'কাউন্টার',
      'target': 'লক্ষ্য',
      'reset': 'রিসেট',
      'continue': 'চালিয়ে যান',
      'cancel': 'বাতিল',
      'ok': 'ঠিক আছে',
      'settings': 'সেটিংস',
      'theme': 'থিম',
      'language': 'ভাষা',
      'vibration': 'কম্পন',
      'sound': 'শব্দ',
      'success_title': 'মাশাআল্লাহ! 🎉',
      'success_message': 'লক্ষ্য পৌঁছেছে!',
      'goals': 'লক্ষ্য',
      'dailyGoal': 'দৈনিক লক্ষ্য',
      'weeklyGoal': 'সাপ্তাহিক লক্ষ্য',
      'monthlyGoal': 'মাসিক লক্ষ্য',
      'progress': 'অগ্রগতি',
      'statistics': 'পরিসংখ্যান',
      'today': 'আজ',
      'total': 'মোট',
      'streak': 'ধারা',
      'consecutiveDays': 'পরপর দিন',
      'last7Days': 'শেষ ৭ দিন',
      'days': 'দিন',
      'select_zikr': 'জিকির নির্বাচন করুন',
      'add_zikr': 'জিকির যোগ করুন',
      'custom_zikrs': 'কাস্টম জিকির',
      'zikr_name_ar': 'আরবি নাম',
      'zikr_name_tr': 'তুর্কি নাম',
      'zikr_name_en': 'ইংরেজি নাম',
      'zikr_name_id': 'ইন্দোনেশীয় নাম',
      'zikr_name_ur': 'উর্দু নাম',
      'zikr_name_bn': 'বাংলা নাম',
      'zikr_name_ms': 'মালয় নাম',
      'zikr_name_fa': 'ফার্সি নাম',
      'zikr_name_fr': 'ফরাসি নাম',
      'zikr_name_zh': 'চীনা নাম',
      'zikr_name_ja': 'জাপানি নাম',
      'zikr_name_ru': 'রাশিয়ান নাম',
      'zikr_name_de': 'জার্মান নাম',
      'zikr_name_sw': 'সোয়াহিলি নাম',
      'zikr_name_ha': 'হাউসা নাম',
      'default_count': 'ডিফল্ট সংখ্যা',
      'set_target': 'লক্ষ্য নির্ধারণ করুন',
      'quick_select': 'দ্রুত নির্বাচন',
      'custom_target': 'কাস্টম লক্ষ্য',
      'enter_target': 'লক্ষ্য সংখ্যা লিখুন',
      'setGoal': 'লক্ষ্য নির্ধারণ',
      'goalCompleted': 'লক্ষ্য সম্পন্ন! 🎯',
      'zikr_count': 'জিকির',
      'edit': 'সম্পাদনা',
      'delete': 'মুছুন',
      'save': 'সংরক্ষণ',
      'trophies': 'ট্রফি',
      'streak_continues': 'ধারা অব্যাহত',
      'new_record': 'নতুন রেকর্ড!',
      'achievement_streaks': 'অর্জন ধারা',
      'weeks': 'সপ্তাহ',
      'months': 'মাস',
      'last_4_weeks': 'শেষ ৪ সপ্তাহ',
      'last_12_months': 'শেষ ১২ মাস',
      'optional': 'ঐচ্ছিক',
      'required': 'প্রয়োজনীয়',
      'transliteration': 'প্রতিবর্ণীকরণ',
      'version': 'সংস্করণ 1.0.0',
      'support_us': 'আমাদের সমর্থন করুন',
      'support_description': 'একটি সংক্ষিপ্ত বিজ্ঞাপন দেখে এই অ্যাপটি বিনামূল্যে রাখতে আমাদের সাহায্য করুন। আপনার সমর্থন অনেক গুরুত্বপূর্ণ!',
      'watch_ad': 'বিজ্ঞাপন দেখুন',
      'ad_not_ready': 'বিজ্ঞাপন প্রস্তুত নয়, অনুগ্রহ করে আবার চেষ্টা করুন',
      'thank_you_support': 'আপনার সমর্থনের জন্য ধন্যবাদ! 🙏',
      'features': 'বৈশিষ্ট্য',
      'feature_goals': 'দৈনিক, সাপ্তাহিক, মাসিক লক্ষ্য',
      'feature_statistics': 'বিস্তারিত পরিসংখ্যান',
      'feature_widget': 'হোম স্ক্রিন উইজেট',
      'feature_languages': '১৫টি ভাষার সমর্থন',
    },
    // Malayca (Malezya)
    'ms': {
      'app_name': 'Kaunter Tasbih',
      'counter': 'Kaunter',
      'target': 'Sasaran',
      'reset': 'Set Semula',
      'continue': 'Teruskan',
      'cancel': 'Batal',
      'ok': 'OK',
      'settings': 'Tetapan',
      'theme': 'Tema',
      'language': 'Bahasa',
      'vibration': 'Getaran',
      'sound': 'Bunyi',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Sasaran tercapai!',
      'goals': 'Matlamat',
      'dailyGoal': 'Matlamat Harian',
      'weeklyGoal': 'Matlamat Mingguan',
      'monthlyGoal': 'Matlamat Bulanan',
      'progress': 'Kemajuan',
      'statistics': 'Statistik',
      'today': 'Hari Ini',
      'total': 'Jumlah',
      'streak': 'Berturut-turut',
      'consecutiveDays': 'Hari berturut-turut',
      'last7Days': '7 Hari Terakhir',
      'days': 'hari',
      'select_zikr': 'Pilih Zikir',
      'add_zikr': 'Tambah Zikir',
      'custom_zikrs': 'Zikir Tersuai',
      'zikr_name_ar': 'Nama Arab',
      'zikr_name_tr': 'Nama Turki',
      'zikr_name_en': 'Nama Inggeris',
      'zikr_name_id': 'Nama Indonesia',
      'zikr_name_ur': 'Nama Urdu',
      'zikr_name_bn': 'Nama Bengali',
      'zikr_name_ms': 'Nama Melayu',
      'zikr_name_fa': 'Nama Parsi',
      'zikr_name_fr': 'Nama Perancis',
      'zikr_name_zh': 'Nama Cina',
      'zikr_name_ja': 'Nama Jepun',
      'zikr_name_ru': 'Nama Rusia',
      'zikr_name_de': 'Nama Jerman',
      'zikr_name_sw': 'Nama Swahili',
      'zikr_name_ha': 'Nama Hausa',
      'default_count': 'Kiraan Lalai',
      'set_target': 'Tetapkan Sasaran',
      'quick_select': 'Pilihan Pantas',
      'custom_target': 'Sasaran Tersuai',
      'enter_target': 'Masukkan nombor sasaran',
      'setGoal': 'Tetapkan Matlamat',
      'goalCompleted': 'Matlamat Tercapai! 🎯',
      'zikr_count': 'Zikir',
      'edit': 'Edit',
      'delete': 'Padam',
      'save': 'Simpan',
      'trophies': 'Trofi',
      'streak_continues': 'berturut-turut berterusan',
      'new_record': 'Rekod baharu!',
      'achievement_streaks': 'Pencapaian Berturut-turut',
      'weeks': 'Minggu',
      'months': 'Bulan',
      'last_4_weeks': '4 Minggu Terakhir',
      'last_12_months': '12 Bulan Terakhir',
      'optional': 'Pilihan',
      'required': 'diperlukan',
      'transliteration': 'Transliterasi',
      'version': 'Versi 1.0.0',
      'support_us': 'Sokong Kami',
      'support_description': 'Bantu kami mengekalkan aplikasi ini percuma dengan menonton iklan pendek. Sokongan anda sangat bermakna!',
      'watch_ad': 'Tonton Iklan',
      'ad_not_ready': 'Iklan belum sedia, sila cuba lagi',
      'thank_you_support': 'Terima kasih atas sokongan anda! 🙏',
      'features': 'Ciri-ciri',
      'feature_goals': 'Matlamat Harian, Mingguan, Bulanan',
      'feature_statistics': 'Statistik Terperinci',
      'feature_widget': 'Widget Skrin Utama',
      'feature_languages': 'Sokongan 15 Bahasa',
    },
    // Farsça (İran)
    'fa': {
      'app_name': 'شمارنده تسبیح',
      'counter': 'شمارنده',
      'target': 'هدف',
      'reset': 'بازنشانی',
      'continue': 'ادامه',
      'cancel': 'لغو',
      'ok': 'تأیید',
      'settings': 'تنظیمات',
      'theme': 'تم',
      'language': 'زبان',
      'vibration': 'لرزش',
      'sound': 'صدا',
      'success_title': 'ماشاءالله! 🎉',
      'success_message': 'به هدف رسیدید!',
      'goals': 'اهداف',
      'dailyGoal': 'هدف روزانه',
      'weeklyGoal': 'هدف هفتگی',
      'monthlyGoal': 'هدف ماهانه',
      'progress': 'پیشرفت',
      'statistics': 'آمار',
      'today': 'امروز',
      'total': 'کل',
      'streak': 'رشته',
      'consecutiveDays': 'روزهای متوالی',
      'last7Days': '7 روز گذشته',
      'days': 'روز',
      'select_zikr': 'انتخاب ذکر',
      'add_zikr': 'افزودن ذکر',
      'custom_zikrs': 'ذکرهای سفارشی',
      'zikr_name_ar': 'نام عربی',
      'zikr_name_tr': 'نام ترکی',
      'zikr_name_en': 'نام انگلیسی',
      'default_count': 'تعداد پیش‌فرض',
      'set_target': 'تعیین هدف',
      'quick_select': 'انتخاب سریع',
      'custom_target': 'هدف سفارشی',
      'enter_target': 'شماره هدف را وارد کنید',
      'setGoal': 'تعیین هدف',
      'goalCompleted': 'هدف تکمیل شد! 🎯',
      'zikr_count': 'ذکر',
      'edit': 'ویرایش',
      'delete': 'حذف',
      'save': 'ذخیره',
      'trophies': 'جوایز',
      'streak_continues': 'رشته ادامه دارد',
      'new_record': 'رکورد جدید!',
      'achievement_streaks': 'رشتههای موفقیت',
      'weeks': 'هفته',
      'months': 'ماه',
      'last_4_weeks': '4 هفته گذشته',
      'last_12_months': '12 ماه گذشته',
      'optional': 'اختیاری',
      'required': 'ضروری',
      'transliteration': 'نویسه‌گردانی',
      'version': 'نسخه 1.0.0',
      'support_us': 'از ما حمایت کنید',
      'support_description': 'با تماشای یک تبلیغ کوتاه به ما کمک کنید این برنامه را رایگان نگه داریم. حمایت شما بسیار ارزشمند است!',
      'watch_ad': 'تماشای تبلیغ',
      'ad_not_ready': 'تبلیغ آماده نیست، لطفاً دوباره امتحان کنید',
      'thank_you_support': 'از حمایت شما متشکریم! 🙏',
      'features': 'ویژگی‌ها',
      'feature_goals': 'اهداف روزانه، هفتگی، ماهانه',
      'feature_statistics': 'آمار تفصیلی',
      'feature_widget': 'ویجت صفحه اصلی',
      'feature_languages': 'پشتیبانی از 15 زبان',
    },
    // Fransızca (Kuzey Afrika)
    'fr': {
      'app_name': 'Compteur Tasbih',
      'counter': 'Compteur',
      'target': 'Objectif',
      'reset': 'Réinitialiser',
      'continue': 'Continuer',
      'cancel': 'Annuler',
      'ok': 'OK',
      'settings': 'Paramètres',
      'theme': 'Thème',
      'language': 'Langue',
      'vibration': 'Vibration',
      'sound': 'Son',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Objectif atteint!',
      'goals': 'Objectifs',
      'dailyGoal': 'Objectif Quotidien',
      'weeklyGoal': 'Objectif Hebdomadaire',
      'monthlyGoal': 'Objectif Mensuel',
      'progress': 'Progrès',
      'statistics': 'Statistiques',
      'today': "Aujourd'hui",
      'total': 'Total',
      'streak': 'Série',
      'consecutiveDays': 'Jours consécutifs',
      'last7Days': '7 Derniers Jours',
      'days': 'jours',
      'select_zikr': 'Sélectionner Dhikr',
      'add_zikr': 'Ajouter Dhikr',
      'custom_zikrs': 'Dhikrs Personnalisés',
      'zikr_name_ar': 'Nom Arabe',
      'zikr_name_tr': 'Nom Turc',
      'zikr_name_en': 'Nom Anglais',
      'zikr_name_id': 'Nom Indonésien',
      'zikr_name_ur': 'Nom Ourdou',
      'zikr_name_bn': 'Nom Bengali',
      'zikr_name_ms': 'Nom Malais',
      'zikr_name_fa': 'Nom Persan',
      'zikr_name_fr': 'Nom Français',
      'zikr_name_zh': 'Nom Chinois',
      'zikr_name_ja': 'Nom Japonais',
      'zikr_name_ru': 'Nom Russe',
      'zikr_name_de': 'Nom Allemand',
      'zikr_name_sw': 'Nom Swahili',
      'zikr_name_ha': 'Nom Haoussa',
      'set_target': 'Définir Objectif',
      'quick_select': 'Sélection Rapide',
      'custom_target': 'Objectif Personnalisé',
      'enter_target': 'Entrez le numéro cible',
      'setGoal': 'Définir Objectif',
      'goalCompleted': 'Objectif Atteint! 🎯',
      'zikr_count': 'Dhikr',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'save': 'Enregistrer',
      'trophies': 'Trophées',
      'streak_continues': 'série continue',
      'new_record': 'Nouveau record!',
      'achievement_streaks': 'Séries de Réussite',
      'weeks': 'Semaines',
      'months': 'Mois',
      'last_4_weeks': '4 Dernières Semaines',
      'last_12_months': '12 Derniers Mois',
      'optional': 'Optionnel',
      'required': 'requis',
      'transliteration': 'Translittération',
      'version': 'Version 1.0.0',
      'support_us': 'Soutenez-nous',
      'support_description': 'Aidez-nous à garder cette application gratuite en regardant une courte publicité. Votre soutien compte beaucoup!',
      'watch_ad': 'Regarder la Publicité',
      'ad_not_ready': 'Publicité non prête, veuillez réessayer',
      'thank_you_support': 'Merci pour votre soutien! 🙏',
      'features': 'Fonctionnalités',
      'feature_goals': 'Objectifs Quotidiens, Hebdomadaires, Mensuels',
      'feature_statistics': 'Statistiques Détaillées',
      'feature_widget': 'Widget Écran d\'Accueil',
      'feature_languages': 'Support de 15 Langues',
    },
    // Çince (Çin)
    'zh': {
      'app_name': '计数器',
      'counter': '计数器',
      'target': '目标',
      'reset': '重置',
      'continue': '继续',
      'cancel': '取消',
      'ok': '确定',
      'settings': '设置',
      'theme': '主题',
      'language': '语言',
      'vibration': '震动',
      'sound': '声音',
      'success_title': '太棒了! 🎉',
      'success_message': '目标达成!',
      'goals': '目标',
      'dailyGoal': '每日目标',
      'weeklyGoal': '每周目标',
      'monthlyGoal': '每月目标',
      'progress': '进度',
      'statistics': '统计',
      'today': '今天',
      'total': '总计',
      'streak': '连续',
      'consecutiveDays': '连续天数',
      'last7Days': '最近7天',
      'days': '天',
      'select_zikr': '选择念诵',
      'add_zikr': '添加念诵',
      'custom_zikrs': '自定义念诵',
      'zikr_name_ar': '阿拉伯名称',
      'zikr_name_tr': '土耳其名称',
      'zikr_name_en': '英文名称',
      'zikr_name_id': '印尼名称',
      'zikr_name_ur': '乌尔都名称',
      'zikr_name_bn': '孟加拉名称',
      'zikr_name_ms': '马来名称',
      'zikr_name_fa': '波斯名称',
      'zikr_name_fr': '法语名称',
      'zikr_name_zh': '中文名称',
      'zikr_name_ja': '日语名称',
      'zikr_name_ru': '俄语名称',
      'zikr_name_de': '德语名称',
      'zikr_name_sw': '斯瓦希里名称',
      'zikr_name_ha': '豪萨名称',
      'set_target': '设定目标',
      'quick_select': '快速选择',
      'custom_target': '自定义目标',
      'enter_target': '输入目标数字',
      'setGoal': '设定目标',
      'goalCompleted': '目标完成！🎯',
      'zikr_count': '念诵',
      'edit': '编辑',
      'delete': '删除',
      'save': '保存',
      'trophies': '奖杯',
      'streak_continues': '连续继续',
      'new_record': '新纪录！',
      'achievement_streaks': '成就连续',
      'weeks': '周',
      'months': '月',
      'last_4_weeks': '最近4周',
      'last_12_months': '最近12个月',
      'optional': '可选',
      'required': '必需',
      'transliteration': '音译',
      'version': '版本 1.0.0',
      'support_us': '支持我们',
      'support_description': '通过观看短广告帮助我们保持此应用免费。您的支持意义重大!',
      'watch_ad': '观看广告',
      'ad_not_ready': '广告未准备好，请重试',
      'thank_you_support': '感谢您的支持! 🙏',
      'features': '功能',
      'feature_goals': '每日、每周、每月目标',
      'feature_statistics': '详细统计',
      'feature_widget': '主屏幕小部件',
      'feature_languages': '支持15种语言',
    },
    // Japonca (Japonya)
    'ja': {
      'app_name': 'カウンター',
      'counter': 'カウンター',
      'target': '目標',
      'reset': 'リセット',
      'continue': '続ける',
      'cancel': 'キャンセル',
      'ok': 'OK',
      'settings': '設定',
      'theme': 'テーマ',
      'language': '言語',
      'vibration': '振動',
      'sound': '音',
      'success_title': '素晴らしい! 🎉',
      'success_message': '目標達成!',
      'goals': '目標',
      'dailyGoal': '毎日の目標',
      'weeklyGoal': '毎週の目標',
      'monthlyGoal': '毎月の目標',
      'progress': '進捗',
      'statistics': '統計',
      'today': '今日',
      'total': '合計',
      'streak': '連続',
      'consecutiveDays': '連続日数',
      'last7Days': '過去7日間',
      'days': '日',
      'select_zikr': 'ズィクルを選択',
      'add_zikr': 'ズィクルを追加',
      'custom_zikrs': 'カスタムズィクル',
      'zikr_name_ar': 'アラビア語名',
      'zikr_name_tr': 'トルコ語名',
      'zikr_name_en': '英語名',
      'zikr_name_id': 'インドネシア語名',
      'zikr_name_ur': 'ウルドゥー語名',
      'zikr_name_bn': 'ベンガル語名',
      'zikr_name_ms': 'マレー語名',
      'zikr_name_fa': 'ペルシア語名',
      'zikr_name_fr': 'フランス語名',
      'zikr_name_zh': '中国語名',
      'zikr_name_ja': '日本語名',
      'zikr_name_ru': 'ロシア語名',
      'zikr_name_de': 'ドイツ語名',
      'zikr_name_sw': 'スワヒリ語名',
      'zikr_name_ha': 'ハウサ語名',
      'set_target': '目標を設定',
      'quick_select': 'クイック選択',
      'custom_target': 'カスタム目標',
      'enter_target': '目標番号を入力',
      'setGoal': '目標を設定',
      'goalCompleted': '目標達成！🎯',
      'zikr_count': 'ズィクル',
      'edit': '編集',
      'delete': '削除',
      'save': '保存',
      'trophies': 'トロフィー',
      'streak_continues': '連続継続',
      'new_record': '新記録！',
      'achievement_streaks': '達成連続',
      'weeks': '週',
      'months': '月',
      'last_4_weeks': '過去4週間',
      'last_12_months': '過去12ヶ月',
      'optional': 'オプション',
      'required': '必須',
      'transliteration': '音訳',
      'version': 'バージョン 1.0.0',
      'support_us': 'サポート',
      'support_description': '短い広告を視聴して、このアプリを無料で維持するのを手伝ってください。あなたのサポートは大きな意味があります!',
      'watch_ad': '広告を見る',
      'ad_not_ready': '広告の準備ができていません。もう一度お試しください',
      'thank_you_support': 'ご支援ありがとうございます! 🙏',
      'features': '機能',
      'feature_goals': '毎日、毎週、毎月の目標',
      'feature_statistics': '詳細な統計',
      'feature_widget': 'ホーム画面ウィジェット',
      'feature_languages': '15言語サポート',
    },
    // Rusça (Rusya)
    'ru': {
      'app_name': 'Счётчик',
      'counter': 'Счётчик',
      'target': 'Цель',
      'reset': 'Сброс',
      'continue': 'Продолжить',
      'cancel': 'Отмена',
      'ok': 'OK',
      'settings': 'Настройки',
      'theme': 'Тема',
      'language': 'Язык',
      'vibration': 'Вибрация',
      'sound': 'Звук',
      'success_title': 'Отлично! 🎉',
      'success_message': 'Цель достигнута!',
      'goals': 'Цели',
      'dailyGoal': 'Ежедневная цель',
      'weeklyGoal': 'Еженедельная цель',
      'monthlyGoal': 'Ежемесячная цель',
      'progress': 'Прогресс',
      'statistics': 'Статистика',
      'today': 'Сегодня',
      'total': 'Всего',
      'streak': 'Серия',
      'consecutiveDays': 'Дней подряд',
      'last7Days': 'Последние 7 дней',
      'days': 'дней',
      'select_zikr': 'Выбрать Зикр',
      'add_zikr': 'Добавить Зикр',
      'custom_zikrs': 'Пользовательские Зикры',
      'zikr_name_ar': 'Арабское Имя',
      'zikr_name_tr': 'Турецкое Имя',
      'zikr_name_en': 'Английское Имя',
      'zikr_name_id': 'Индонезийское Имя',
      'zikr_name_ur': 'Имя на Урду',
      'zikr_name_bn': 'Бенгальское Имя',
      'zikr_name_ms': 'Малайское Имя',
      'zikr_name_fa': 'Персидское Имя',
      'zikr_name_fr': 'Французское Имя',
      'zikr_name_zh': 'Китайское Имя',
      'zikr_name_ja': 'Японское Имя',
      'zikr_name_ru': 'Русское Имя',
      'zikr_name_de': 'Немецкое Имя',
      'zikr_name_sw': 'Имя на Суахили',
      'zikr_name_ha': 'Имя на Хауса',
      'set_target': 'Установить Цель',
      'quick_select': 'Быстрый Выбор',
      'custom_target': 'Пользовательская Цель',
      'enter_target': 'Введите целевой номер',
      'setGoal': 'Установить Цель',
      'goalCompleted': 'Цель Достигнута! 🎯',
      'zikr_count': 'Зикр',
      'edit': 'Редактировать',
      'delete': 'Удалить',
      'save': 'Сохранить',
      'trophies': 'Трофеи',
      'streak_continues': 'серия продолжается',
      'new_record': 'Новый рекорд!',
      'achievement_streaks': 'Серии Достижений',
      'weeks': 'Недели',
      'months': 'Месяцы',
      'last_4_weeks': 'Последние 4 Недели',
      'last_12_months': 'Последние 12 Месяцев',
      'optional': 'Необязательно',
      'required': 'обязательно',
      'transliteration': 'Транслитерация',
      'version': 'Версия 1.0.0',
      'support_us': 'Поддержите нас',
      'support_description': 'Помогите нам сохранить это приложение бесплатным, просмотрев короткую рекламу. Ваша поддержка очень важна!',
      'watch_ad': 'Смотреть Рекламу',
      'ad_not_ready': 'Реклама не готова, попробуйте еще раз',
      'thank_you_support': 'Спасибо за вашу поддержку! 🙏',
      'features': 'Функции',
      'feature_goals': 'Ежедневные, Еженедельные, Ежемесячные Цели',
      'feature_statistics': 'Подробная Статистика',
      'feature_widget': 'Виджет Главного Экрана',
      'feature_languages': 'Поддержка 15 Языков',
    },
    // Almanca (Almanya)
    'de': {
      'app_name': 'Zähler',
      'counter': 'Zähler',
      'target': 'Ziel',
      'reset': 'Zurücksetzen',
      'continue': 'Weiter',
      'cancel': 'Abbrechen',
      'ok': 'OK',
      'settings': 'Einstellungen',
      'theme': 'Thema',
      'language': 'Sprache',
      'vibration': 'Vibration',
      'sound': 'Ton',
      'success_title': 'Ausgezeichnet! 🎉',
      'success_message': 'Ziel erreicht!',
      'goals': 'Ziele',
      'dailyGoal': 'Tägliches Ziel',
      'weeklyGoal': 'Wöchentliches Ziel',
      'monthlyGoal': 'Monatliches Ziel',
      'progress': 'Fortschritt',
      'statistics': 'Statistiken',
      'today': 'Heute',
      'total': 'Gesamt',
      'streak': 'Serie',
      'consecutiveDays': 'Aufeinanderfolgende Tage',
      'last7Days': 'Letzte 7 Tage',
      'days': 'Tage',
      'select_zikr': 'Dhikr Auswählen',
      'add_zikr': 'Dhikr Hinzufügen',
      'custom_zikrs': 'Benutzerdefinierte Dhikrs',
      'zikr_name_ar': 'Arabischer Name',
      'zikr_name_tr': 'Türkischer Name',
      'zikr_name_en': 'Englischer Name',
      'zikr_name_id': 'Indonesischer Name',
      'zikr_name_ur': 'Urdu-Name',
      'zikr_name_bn': 'Bengalischer Name',
      'zikr_name_ms': 'Malaiischer Name',
      'zikr_name_fa': 'Persischer Name',
      'zikr_name_fr': 'Französischer Name',
      'zikr_name_zh': 'Chinesischer Name',
      'zikr_name_ja': 'Japanischer Name',
      'zikr_name_ru': 'Russischer Name',
      'zikr_name_de': 'Deutscher Name',
      'zikr_name_sw': 'Swahili-Name',
      'zikr_name_ha': 'Hausa-Name',
      'set_target': 'Ziel Festlegen',
      'quick_select': 'Schnellauswahl',
      'custom_target': 'Benutzerdefiniertes Ziel',
      'enter_target': 'Zielnummer eingeben',
      'setGoal': 'Ziel Festlegen',
      'goalCompleted': 'Ziel Erreicht! 🎯',
      'zikr_count': 'Dhikr',
      'edit': 'Bearbeiten',
      'delete': 'Löschen',
      'save': 'Speichern',
      'trophies': 'Trophäen',
      'streak_continues': 'Serie geht weiter',
      'new_record': 'Neuer Rekord!',
      'achievement_streaks': 'Erfolgsserien',
      'weeks': 'Wochen',
      'months': 'Monate',
      'last_4_weeks': 'Letzte 4 Wochen',
      'last_12_months': 'Letzte 12 Monate',
      'optional': 'Optional',
      'required': 'erforderlich',
      'transliteration': 'Transliteration',
      'version': 'Version 1.0.0',
      'support_us': 'Unterstützen Sie uns',
      'support_description': 'Helfen Sie uns, diese App kostenlos zu halten, indem Sie eine kurze Werbung ansehen. Ihre Unterstützung bedeutet viel!',
      'watch_ad': 'Werbung Ansehen',
      'ad_not_ready': 'Werbung nicht bereit, bitte versuchen Sie es erneut',
      'thank_you_support': 'Vielen Dank für Ihre Unterstützung! 🙏',
      'features': 'Funktionen',
      'feature_goals': 'Tägliche, Wöchentliche, Monatliche Ziele',
      'feature_statistics': 'Detaillierte Statistiken',
      'feature_widget': 'Startbildschirm-Widget',
      'feature_languages': 'Unterstützung für 15 Sprachen',
    },
    // Svahili (Doğu Afrika)
    'sw': {
      'app_name': 'Kihesabu',
      'counter': 'Kihesabu',
      'target': 'Lengo',
      'reset': 'Weka Upya',
      'continue': 'Endelea',
      'cancel': 'Ghairi',
      'ok': 'Sawa',
      'settings': 'Mipangilio',
      'theme': 'Mandhari',
      'language': 'Lugha',
      'vibration': 'Mtetemo',
      'sound': 'Sauti',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Lengo limefikiwa!',
      'goals': 'Malengo',
      'dailyGoal': 'Lengo la Kila Siku',
      'weeklyGoal': 'Lengo la Kila Wiki',
      'monthlyGoal': 'Lengo la Kila Mwezi',
      'progress': 'Maendeleo',
      'statistics': 'Takwimu',
      'today': 'Leo',
      'total': 'Jumla',
      'streak': 'Mfululizo',
      'consecutiveDays': 'Siku za mfululizo',
      'last7Days': 'Siku 7 Zilizopita',
      'days': 'siku',
      'select_zikr': 'Chagua Dhikr',
      'add_zikr': 'Ongeza Dhikr',
      'custom_zikrs': 'Dhikr Maalum',
      'zikr_name_ar': 'Jina la Kiarabu',
      'zikr_name_tr': 'Jina la Kituruki',
      'zikr_name_en': 'Jina la Kiingereza',
      'zikr_name_id': 'Jina la Kiindonesia',
      'zikr_name_ur': 'Jina la Kiurdu',
      'zikr_name_bn': 'Jina la Kibengali',
      'zikr_name_ms': 'Jina la Kimalesia',
      'zikr_name_fa': 'Jina la Kiajemi',
      'zikr_name_fr': 'Jina la Kifaransa',
      'zikr_name_zh': 'Jina la Kichina',
      'zikr_name_ja': 'Jina la Kijapani',
      'zikr_name_ru': 'Jina la Kirusi',
      'zikr_name_de': 'Jina la Kijerumani',
      'zikr_name_sw': 'Jina la Kiswahili',
      'zikr_name_ha': 'Jina la Kihausa',
      'set_target': 'Weka Lengo',
      'quick_select': 'Uchaguzi wa Haraka',
      'custom_target': 'Lengo Maalum',
      'enter_target': 'Weka nambari ya lengo',
      'setGoal': 'Weka Lengo',
      'goalCompleted': 'Lengo Limefikiwa! 🎯',
      'zikr_count': 'Dhikr',
      'edit': 'Hariri',
      'delete': 'Futa',
      'save': 'Hifadhi',
      'trophies': 'Tuzo',
      'streak_continues': 'mfululizo unaendelea',
      'new_record': 'Rekodi mpya!',
      'achievement_streaks': 'Mfululizo wa Mafanikio',
      'weeks': 'Wiki',
      'months': 'Miezi',
      'last_4_weeks': 'Wiki 4 Zilizopita',
      'last_12_months': 'Miezi 12 Iliyopita',
      'optional': 'Hiari',
      'required': 'inahitajika',
      'transliteration': 'Tafsiri ya Herufi',
      'version': 'Toleo 1.0.0',
      'support_us': 'Tusaidie',
      'support_description': 'Tusaidie kuweka programu hii bure kwa kutazama tangazo fupi. Msaada wako una maana sana!',
      'watch_ad': 'Tazama Tangazo',
      'ad_not_ready': 'Tangazo halijawa tayari, tafadhali jaribu tena',
      'thank_you_support': 'Asante kwa msaada wako! 🙏',
      'features': 'Vipengele',
      'feature_goals': 'Malengo ya Kila Siku, Kila Wiki, Kila Mwezi',
      'feature_statistics': 'Takwimu za Kina',
      'feature_widget': 'Widget ya Skrini Kuu',
      'feature_languages': 'Msaada wa Lugha 15',
    },
    // Hausa (Batı Afrika)
    'ha': {
      'app_name': 'Mai Ƙidaya',
      'counter': 'Mai Ƙidaya',
      'target': 'Manufa',
      'reset': 'Sake Saita',
      'continue': 'Ci gaba',
      'cancel': 'Soke',
      'ok': 'To',
      'settings': 'Saitunan',
      'theme': 'Jigo',
      'language': 'Harshe',
      'vibration': 'Girgiza',
      'sound': 'Sauti',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'An cimma manufa!',
      'goals': 'Manufofi',
      'dailyGoal': 'Manufar Yau da Kullum',
      'weeklyGoal': 'Manufar Mako-mako',
      'monthlyGoal': 'Manufar Wata-wata',
      'progress': 'Ci gaba',
      'statistics': 'Kididdiga',
      'today': 'Yau',
      'total': 'Jimla',
      'streak': 'Jeri',
      'consecutiveDays': 'Kwanaki a jere',
      'last7Days': 'Kwanaki 7 da suka gabata',
      'days': 'kwanaki',
      'select_zikr': 'Zaɓi Zikiri',
      'add_zikr': 'Ƙara Zikiri',
      'custom_zikrs': 'Zikiri na Musamman',
      'zikr_name_ar': 'Sunan Larabci',
      'zikr_name_tr': 'Sunan Turkiyya',
      'zikr_name_en': 'Sunan Turanci',
      'zikr_name_id': 'Sunan Indonesiya',
      'zikr_name_ur': 'Sunan Urdu',
      'zikr_name_bn': 'Sunan Bengali',
      'zikr_name_ms': 'Sunan Malay',
      'zikr_name_fa': 'Sunan Farisa',
      'zikr_name_fr': 'Sunan Faransanci',
      'zikr_name_zh': 'Sunan Sinanci',
      'zikr_name_ja': 'Sunan Jafananci',
      'zikr_name_ru': 'Sunan Rashanci',
      'zikr_name_de': 'Sunan Jamusanci',
      'zikr_name_sw': 'Sunan Swahili',
      'zikr_name_ha': 'Sunan Hausa',
      'set_target': 'Saita Manufa',
      'quick_select': 'Zaɓi da Sauri',
      'custom_target': 'Manufa ta Musamman',
      'enter_target': 'Shigar da lambar manufa',
      'setGoal': 'Saita Manufa',
      'goalCompleted': 'An Cimma Manufa! 🎯',
      'zikr_count': 'Zikiri',
      'edit': 'Gyara',
      'delete': 'Goge',
      'save': 'Ajiye',
      'trophies': 'Kyautuka',
      'streak_continues': 'jeri yana ci gaba',
      'new_record': 'Sabon rikodin!',
      'achievement_streaks': 'Jerin Nasara',
      'weeks': 'Makonni',
      'months': 'Watanni',
      'last_4_weeks': 'Makonni 4 da suka gabata',
      'last_12_months': 'Watanni 12 da suka gabata',
      'optional': 'Na Zaɓi',
      'required': 'ana bukata',
      'transliteration': 'Fassarar Haruffa',
      'version': 'Sigar 1.0.0',
      'support_us': 'Tallafa Mana',
      'support_description': 'Taimaka mana mu kiyaye wannan app kyauta ta hanyar kallon gajeren talla. Goyon bayanku yana da mahimmanci!',
      'watch_ad': 'Kalli Talla',
      'ad_not_ready': 'Talla ba ta shirye ba, don Allah sake gwadawa',
      'thank_you_support': 'Mun gode da goyon bayanku! 🙏',
      'features': 'Fasaloli',
      'feature_goals': 'Manufofin Yau da Kullum, Mako-mako, Wata-wata',
      'feature_statistics': 'Cikakkun Kididdiga',
      'feature_widget': 'Widget na Babban Allo',
      'feature_languages': 'Tallafin Harsuna 15',
    },
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }

  String get appName => translate('app_name');
  String get counter => translate('counter');
  String get target => translate('target');
  String get reset => translate('reset');
  String get continueText => translate('continue');
  String get cancel => translate('cancel');
  String get ok => translate('ok');
  String get settings => translate('settings');
  String get theme => translate('theme');
  String get language => translate('language');
  String get vibration => translate('vibration');
  String get sound => translate('sound');
  String get selectZikr => translate('select_zikr');
  String get addZikr => translate('add_zikr');
  String get customZikrs => translate('custom_zikrs');
  String get zikrNameAr => translate('zikr_name_ar');
  String get zikrNameTr => translate('zikr_name_tr');
  String get zikrNameEn => translate('zikr_name_en');
  String get defaultCount => translate('default_count');
  String get setTarget => translate('set_target');
  String get quickSelect => translate('quick_select');
  String get customTarget => translate('custom_target');
  String get enterTarget => translate('enter_target');
  String get successTitle => translate('success_title');
  String get successMessage => translate('success_message');
  String get zikrCount => translate('zikr_count');
  String get edit => translate('edit');
  String get delete => translate('delete');
  String get save => translate('save');
  String get arabic => translate('arabic');
  String get turkish => translate('turkish');
  String get english => translate('english');
  String get indonesian => translate('indonesian');
  String get incrementCounter => translate('incrementCounter');
  String get resetCounter => translate('resetCounter');
  String get changeTarget => translate('changeTarget');
  String get vibrationOn => translate('vibrationOn');
  String get vibrationOff => translate('vibrationOff');
  String get soundOn => translate('soundOn');
  String get soundOff => translate('soundOff');
  String get about => translate('about');
  String get confettiOn => translate('confettiOn');
  String get confettiOff => translate('confettiOff');
  String get setReminder => translate('setReminder');
  String get cancelReminder => translate('cancelReminder');
  String get goals => translate('goals');
  String get dailyGoal => translate('dailyGoal');
  String get weeklyGoal => translate('weeklyGoal');
  String get monthlyGoal => translate('monthlyGoal');
  String get setGoal => translate('setGoal');
  String get goalCompleted => translate('goalCompleted');
  String get progress => translate('progress');
  String get statistics => translate('statistics');
  String get today => translate('today');
  String get total => translate('total');
  String get streak => translate('streak');
  String get consecutiveDays => translate('consecutiveDays');
  String get last7Days => translate('last7Days');
  String get days => translate('days');
  String get mon => translate('mon');
  String get tue => translate('tue');
  String get wed => translate('wed');
  String get thu => translate('thu');
  String get fri => translate('fri');
  String get sat => translate('sat');
  String get sun => translate('sun');
  String get trophies => translate('trophies');
}
