class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_name': 'Zikirmatik',
      'counter': 'Sayaç',
      'target': 'Hedef',
      'reset': 'Sıfırla',
      'continue': 'Devam Et',
      'cancel': 'İptal',
      'ok': 'Tamam',
      'settings': 'Ayarlar',
      'theme': 'Tema',
      'language': 'Dil',
      'vibration': 'Titreşim',
      'sound': 'Ses',
      'select_zikr': 'Zikir Seç',
      'add_zikr': 'Zikir Ekle',
      'custom_zikrs': 'Özel Zikirler',
      'zikr_name_ar': 'Arapça İsim',
      'zikr_name_tr': 'Türkçe İsim',
      'zikr_name_en': 'İngilizce İsim',
      'zikr_name_id': 'İndonezce İsim',
      'zikr_name_ur': 'Urduca İsim',
      'zikr_name_bn': 'Bengalce İsim',
      'zikr_name_ms': 'Malayca İsim',
      'zikr_name_fa': 'Farsça İsim',
      'zikr_name_fr': 'Fransızca İsim',
      'zikr_name_zh': 'Çince İsim',
      'zikr_name_ja': 'Japonca İsim',
      'zikr_name_ru': 'Rusça İsim',
      'zikr_name_de': 'Almanca İsim',
      'zikr_name_sw': 'Svahili İsim',
      'zikr_name_ha': 'Hausa İsim',
      'contact': 'İletişim',
      'source_code': 'Kaynak Kodu',
      'default_count': 'Varsayılan Adet',
      'set_target': 'Hedef Belirle',
      'quick_select': 'Hızlı Seçim',
      'custom_target': 'Özel Hedef',
      'enter_target': 'Hedef sayısını girin',
      'success_title': 'Maşallah! 🎉',
      'success_message': 'Hedefinize ulaştınız!',
      'zikr_count': 'Zikir',
      'edit': 'Düzenle',
      'delete': 'Sil',
      'save': 'Kaydet',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Sayacı artır',
      'resetCounter': 'Sayacı sıfırla',
      'changeTarget': 'Hedefi değiştir',
      'vibrationOn': 'Titreşim açık',
      'vibrationOff': 'Titreşim kapalı',
      'soundOn': 'Ses açık',
      'soundOff': 'Ses kapalı',
      'about': 'Hakkında',
      'confettiOn': 'Konfeti açık',
      'confettiOff': 'Konfeti kapalı',
      'setReminder': 'Hatırlatıcı Ayarla',
      'cancelReminder': 'İptal Et',
      'goals': 'Hedefler',
      'dailyGoal': 'Günlük Hedef',
      'weeklyGoal': 'Haftalık Hedef',
      'monthlyGoal': 'Aylık Hedef',
      'setGoal': 'Hedef Belirle',
      'goalCompleted': 'Hedef Tamamlandı! 🎯',
      'progress': 'İlerleme',
      'statistics': 'İstatistikler',
      'today': 'Bugün',
      'total': 'Toplam',
      'streak': 'Seri',
      'consecutiveDays': 'Ardışık günler',
      'last7Days': 'Son 7 Gün',
      'days': 'gün',
      'mon': 'Pzt',
      'tue': 'Sal',
      'wed': 'Çar',
      'thu': 'Per',
      'fri': 'Cum',
      'sat': 'Cmt',
      'sun': 'Paz',
      'week_short': 'H',
      'jan': 'Oca',
      'feb': 'Şub',
      'mar': 'Mar',
      'apr': 'Nis',
      'may': 'May',
      'jun': 'Haz',
      'jul': 'Tem',
      'aug': 'Ağu',
      'sep': 'Eyl',
      'oct': 'Eki',
      'nov': 'Kas',
      'dec': 'Ara',
      'trophies': 'Kupalar',
      'streak_continues': 'çizgi devam ediyor',
      'new_record': 'Yeni rekor!',
      'achievement_streaks': 'Başarı Çizgileri',
      'weeks': 'Hafta',
      'months': 'Ay',
      'last_4_weeks': 'Son 4 Hafta',
      'last_12_months': 'Son 12 Ay',
      'optional': 'Opsiyonel',
      'required': 'gerekli',
      'transliteration': 'Okunuş',
      'version': 'Sürüm 1.0.0',
      'support_us': 'Bizi Destekleyin',
      'support_description': 'Kısa bir reklam izleyerek bu uygulamayı ücretsiz tutmamıza yardımcı olun. Desteğiniz bizim için çok değerli!',
      'watch_ad': 'Reklam İzle',
      'ad_not_ready': 'Reklam hazır değil, lütfen tekrar deneyin',
      'thank_you_support': 'Desteğiniz için teşekkür ederiz! 🙏',
      'features': 'Özellikler',
      'feature_goals': 'Günlük, Haftalık, Aylık Hedefler',
      'feature_statistics': 'Detaylı İstatistikler',
      'feature_widget': 'Ana Ekran Widget',
      'feature_languages': '15 Dil Desteği',
      'day_streak': 'Günlük Seri',
      'new_best': 'Yeni Rekor!',
      'completed_today': 'Bugün Tamamlanan',
      'tts': 'Sesli Okuma',
      'ttsOn': 'Sesli okuma açık',
      'ttsOff': 'Sesli okuma kapalı',
      'speak_zikr': 'Zikri Oku',
      'export': 'Dışa Aktar',
      'import': 'İçe Aktar',
      'import_success': 'İçe aktarma başarılı!',
      'import_failed': 'İçe aktarma başarısız',
      'export_success': 'Dışa aktarma başarılı!',
      'export_failed': 'Dışa aktarma başarısız',
      'help_title': 'Uygulama Özellikleri',
      'help_streak_title': 'Seri (Streak) Nedir?',
      'help_streak_text': 'Hedeflerinizi düzenli olarak tamamladığınızda bir "seri" kazanırsınız. Serinizi ne kadar uzun süre devam ettirirseniz, motivasyonunuz o kadar artar. Her gün en az bir hedefi tamamlayarak seriyi canlı tutun!',
      'help_goal_title': 'Hedef (Goal) Nasıl Çalışır?',
      'help_goal_text': 'Günlük, haftalık veya aylık hedefler belirleyebilirsiniz. Örneğin, "günde 1000 zikir" gibi. Hedeflerinize ulaştığınızda özel bildirimler ve animasyonlarla ödüllendirilirsiniz. Hedefler, zikirlerinizi daha planlı bir şekilde çekmenize yardımcı olur.',
      'help_addzikr_title': 'Nasıl Zikir Eklenir?',
      'help_addzikr_text': 'Ana ekrandaki zikir adına dokunarak zikir seçme ekranını açabilirsiniz. Bu ekranda, mevcut zikirler arasından seçim yapabilir veya "Yeni Zikir Ekle" butonuyla kendi özel zikirlerinizi oluşturabilirsiniz.',
      'help_toggles_title': 'Açma/Kapama Butonları',
      'help_toggles_text': 'Ana ekranın altındaki kontrol butonları ile Titreşim, Ses ve Konfeti animasyonu gibi özellikleri anında açıp kapatabilirsiniz. Deneyiminizi kişiselleştirmek için bu ayarları kullanın.',
      'enable_reminder': 'Hatırlatıcıyı Etkinleştir',
      'reminder_enabled': 'Hatırlatıcı Aktif',
      'reminder_disabled': 'Hatırlatıcı Pasif',
      'reminder_set_success': 'Hatırlatıcı başarıyla eklendi!',
      'reminder_set_fail': 'Hatırlatıcı eklenemedi. Lütfen izinleri kontrol edin.',
      'reminder_cancelled': 'Hatırlatıcı başarıyla kaldırıldı.',
      'test_notification_sent': 'Test bildirimi gönderildi!',
      'test': 'Test',
      'close': 'Kapat',
    },
    'en': {
      'app_name': 'Tasbih Counter',
      'counter': 'Counter',
      'enable_reminder': 'Enable Reminder',
      'reminder_enabled': 'Reminder Active',
      'reminder_disabled': 'Reminder Inactive',
      'reminder_set_success': 'Reminder set successfully!',
      'reminder_set_fail': 'Could not set reminder. Please check permissions.',
      'reminder_cancelled': 'Reminder cancelled successfully.',
      'test_notification_sent': 'Test notification sent!',
      'test': 'Test',
      'close': 'Close',
      'target': 'Target',
      'reset': 'Reset',
      'continue': 'Continue',
      'cancel': 'Cancel',
      'ok': 'OK',
      'settings': 'Settings',
      'theme': 'Theme',
      'language': 'Language',
      'vibration': 'Vibration',
      'sound': 'Sound',
      'select_zikr': 'Select Dhikr',
      'add_zikr': 'Add Dhikr',
      'custom_zikrs': 'Custom Dhikrs',
      'zikr_name_ar': 'Arabic Name',
      'zikr_name_tr': 'Turkish Name',
      'zikr_name_en': 'English Name',
      'zikr_name_id': 'Indonesian Name',
      'zikr_name_ur': 'Urdu Name',
      'zikr_name_bn': 'Bengali Name',
      'zikr_name_ms': 'Malay Name',
      'zikr_name_fa': 'Persian Name',
      'zikr_name_fr': 'French Name',
      'zikr_name_zh': 'Chinese Name',
      'zikr_name_ja': 'Japanese Name',
      'zikr_name_ru': 'Russian Name',
      'zikr_name_de': 'German Name',
      'zikr_name_sw': 'Swahili Name',
      'zikr_name_ha': 'Hausa Name',
      'contact': 'Contact',
      'source_code': 'Source Code',
      'default_count': 'Default Count',
      'set_target': 'Set Target',
      'quick_select': 'Quick Select',
      'custom_target': 'Custom Target',
      'enter_target': 'Enter target number',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Target reached!',
      'zikr_count': 'Dhikr',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Increment counter',
      'resetCounter': 'Reset counter',
      'changeTarget': 'Change target',
      'vibrationOn': 'Vibration on',
      'vibrationOff': 'Vibration off',
      'soundOn': 'Sound on',
      'soundOff': 'Sound off',
      'about': 'About',
      'confettiOn': 'Confetti on',
      'confettiOff': 'Confetti off',
      'setReminder': 'Set Reminder',
      'cancelReminder': 'Cancel',
      'goals': 'Goals',
      'dailyGoal': 'Daily Goal',
      'weeklyGoal': 'Weekly Goal',
      'monthlyGoal': 'Monthly Goal',
      'setGoal': 'Set Goal',
      'goalCompleted': 'Goal Completed! 🎯',
      'progress': 'Progress',
      'statistics': 'Statistics',
      'today': 'Today',
      'total': 'Total',
      'streak': 'Streak',
      'consecutiveDays': 'Consecutive days',
      'last7Days': 'Last 7 Days',
      'days': 'days',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'week_short': 'W',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'Mar',
      'apr': 'Apr',
      'may': 'May',
      'jun': 'Jun',
      'jul': 'Jul',
      'aug': 'Aug',
      'sep': 'Sep',
      'oct': 'Oct',
      'nov': 'Nov',
      'dec': 'Dec',
      'trophies': 'Trophies',
      'streak_continues': 'streak continues',
      'new_record': 'New record!',
      'achievement_streaks': 'Achievement Streaks',
      'weeks': 'Weeks',
      'months': 'Months',
      'last_4_weeks': 'Last 4 Weeks',
      'last_12_months': 'Last 12 Months',
      'optional': 'Optional',
      'required': 'required',
      'transliteration': 'Transliteration',
      'version': 'Version 1.0.0',
      'support_us': 'Support Us',
      'support_description': 'Help us keep this app free by watching a short ad. Your support means a lot!',
      'watch_ad': 'Watch Ad',
      'ad_not_ready': 'Ad not ready, please try again',
      'thank_you_support': 'Thank you for your support! 🙏',
      'features': 'Features',
      'feature_goals': 'Daily, Weekly, Monthly Goals',
      'feature_statistics': 'Detailed Statistics',
      'feature_widget': 'Home Screen Widget',
      'feature_languages': '15 Languages Support',
      'day_streak': 'Day Streak',
      'new_best': 'New Best!',
      'completed_today': 'Completed Today',
      'tts': 'Voice Reading',
      'ttsOn': 'Voice reading on',
      'ttsOff': 'Voice reading off',
      'speak_zikr': 'Speak Dhikr',
      'export': 'Export',
      'import': 'Import',
      'import_success': 'Import successful!',
      'import_failed': 'Import failed',
      'export_success': 'Export successful!',
      'export_failed': 'Export failed',
      'help_title': 'App Help',
      'help_streak_title': 'What is a Streak?',
      'help_streak_text': 'When you complete your goals regularly, you earn a streak. The longer you maintain it, the more motivated you stay. Complete at least one goal each day to keep the streak alive!',
      'help_goal_title': 'How Do Goals Work?',
      'help_goal_text': 'You can set daily, weekly, or monthly goals. For example: "1000 dhikr per day". When you reach your goals, you are rewarded with special notifications and animations.',
      'help_addzikr_title': 'How to Add a Dhikr?',
      'help_addzikr_text': 'Tap the dhikr name on the home screen to open the selection screen. Choose from existing dhikrs or create your own with the "Add New Dhikr" button.',
      'help_toggles_title': 'Toggle Buttons',
      'help_toggles_text': 'Use the bottom controls (Vibration, Sound, Confetti) to instantly toggle features and personalize your experience.',
    },
    'ar': {
      'app_name': 'مسبحة إلكترونية',
      'help_title': 'مساعدة التطبيق',
      'help_streak_title': 'ما هي السلسلة (Streak)؟',
      'help_streak_text': 'عند إكمال الأهداف بانتظام، تكسب سلسلة مستمرة. كلما حافظت عليها لفترة أطول، زادت دوافعك. أكمل هدفًا واحدًا على الأقل كل يوم للحفاظ على السلسلة!',
      'help_goal_title': 'كيف تعمل الأهداف؟',
      'help_goal_text': 'يمكنك تحديد أهداف يومية أو أسبوعية أو شهرية. مثلًا: "1000 ذكر يوميًا". عند بلوغ أهدافك، ستحصل على إشعارات ورسوم متحركة خاصة.',
      'help_addzikr_title': 'كيف أضيف ذكرًا؟',
      'help_addzikr_text': 'اضغط على اسم الذكر في الشاشة الرئيسية لفتح شاشة الاختيار. اختر من الأذكار الموجودة أو أنشئ ذكرك الخاص عبر زر "إضافة ذكر جديد".',
      'help_toggles_title': 'أزرار التبديل',
      'help_toggles_text': 'استخدم عناصر التحكم في الأسفل (الاهتزاز، الصوت، والكونفيتي) لتبديل الميزات فورًا وتخصيص تجربتك.',
      'enable_reminder': 'تفعيل التذكير',
      'reminder_enabled': 'التذكير مفعل',
      'reminder_disabled': 'التذكير غير مفعل',
      'reminder_set_success': 'تم ضبط التذكير!',
      'reminder_set_fail': 'تعذر ضبط التذكير. يرجى منح الأذونات.',
      'reminder_cancelled': 'تم إلغاء التذكير.',
      'test_notification_sent': 'تم إرسال إشعار الاختبار!',
      'test': 'اختبار',
      'close': 'إغلاق',
      'counter': 'العداد',
      'target': 'الهدف',
      'reset': 'إعادة تعيين',
      'continue': 'متابعة',
      'cancel': 'إلغاء',
      'ok': 'موافق',
      'settings': 'الإعدادات',
      'theme': 'المظهر',
      'language': 'اللغة',
      'vibration': 'الاهتزاز',
      'sound': 'الصوت',
      'select_zikr': 'اختر الذكر',
      'add_zikr': 'إضافة ذكر',
      'custom_zikrs': 'أذكار مخصصة',
      'zikr_name_ar': 'الاسم بالعربية',
      'zikr_name_tr': 'الاسم بالتركية',
      'zikr_name_en': 'الاسم بالإنجليزية',
      'zikr_name_id': 'الاسم بالإندونيسية',
      'zikr_name_ur': 'الاسم بالأردية',
      'zikr_name_bn': 'الاسم بالبنغالية',
      'zikr_name_ms': 'الاسم بالملايو',
      'zikr_name_fa': 'الاسم بالفارسية',
      'zikr_name_fr': 'الاسم بالفرنسية',
      'zikr_name_zh': 'الاسم بالصينية',
      'zikr_name_ja': 'الاسم باليابانية',
      'zikr_name_ru': 'الاسم بالروسية',
      'zikr_name_de': 'الاسم بالألمانية',
      'zikr_name_sw': 'الاسم بالسواحيلية',
      'zikr_name_ha': 'الاسم بالهوسا',
      'contact': 'اتصل',
      'source_code': 'الكود المصدري',
      'default_count': 'العدد الافتراضي',
      'set_target': 'تحديد الهدف',
      'quick_select': 'اختيار سريع',
      'custom_target': 'هدف مخصص',
      'enter_target': 'أدخل رقم الهدف',
      'success_title': 'ماشاء الله! 🎉',
      'success_message': 'تم الوصول إلى الهدف!',
      'zikr_count': 'ذكر',
      'edit': 'تعديل',
      'delete': 'حذف',
      'save': 'حفظ',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'زيادة العداد',
      'resetCounter': 'إعادة ضبط العداد',
      'changeTarget': 'تغيير الهدف',
      'vibrationOn': 'الاهتزاز قيد التشغيل',
      'vibrationOff': 'الاهتزاز متوقف',
      'soundOn': 'الصوت قيد التشغيل',
      'soundOff': 'الصوت مغلق',
      'about': 'حول',
      'confettiOn': 'الاحتفال مفعل',
      'confettiOff': 'الاحتفال معطل',
      'setReminder': 'تعيين تذكير',
      'cancelReminder': 'إلغاء',
      'goals': 'الأهداف',
      'dailyGoal': 'الهدف اليومي',
      'weeklyGoal': 'الهدف الأسبوعي',
      'monthlyGoal': 'الهدف الشهري',
      'setGoal': 'تحديد الهدف',
      'goalCompleted': 'تم إنجاز الهدف! 🎯',
      'progress': 'التقدم',
      'statistics': 'الإحصائيات',
      'today': 'اليوم',
      'total': 'المجموع',
      'streak': 'السلسلة',
      'consecutiveDays': 'أيام متتالية',
      'last7Days': 'آخر 7 أيام',
      'days': 'أيام',
      'mon': 'الإثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'fri': 'الجمعة',
      'sat': 'السبت',
      'sun': 'الأحد',
      'week_short': 'أ',
      'jan': 'ينا',
      'feb': 'فبر',
      'mar': 'مار',
      'apr': 'أبر',
      'may': 'ماي',
      'jun': 'يون',
      'jul': 'يول',
      'aug': 'أغس',
      'sep': 'سبت',
      'oct': 'أكت',
      'nov': 'نوف',
      'dec': 'ديس',
      'trophies': 'الجوائز',
      'streak_continues': 'السلسلة مستمرة',
      'new_record': 'رقم قياسي جديد!',
      'achievement_streaks': 'سلاسل الإنجاز',
      'weeks': 'أسابيع',
      'months': 'أشهر',
      'last_4_weeks': 'آخر 4 أسابيع',
      'last_12_months': 'آخر 12 شهر',
      'optional': 'اختياري',
      'required': 'مطلوب',
      'transliteration': 'النطق',
      'version': 'الإصدار 1.0.0',
      'support_us': 'ادعمنا',
      'support_description': 'ساعدنا في الحفاظ على هذا التطبيق مجانيًا من خلال مشاهدة إعلان قصير. دعمك يعني الكثير!',
      'watch_ad': 'شاهد الإعلان',
      'ad_not_ready': 'الإعلان غير جاهز، يرجى المحاولة مرة أخرى',
      'thank_you_support': 'شكرا لدعمك! 🙏',
      'features': 'الميزات',
      'feature_goals': 'أهداف يومية وأسبوعية وشهرية',
      'feature_statistics': 'إحصائيات مفصلة',
      'feature_widget': 'ويدجت الشاشة الرئيسية',
      'feature_languages': 'دعم 15 لغة',
      'day_streak': 'سلسلة يومية',
      'new_best': 'أفضل جديد!',
      'completed_today': 'مكتمل اليوم',
      'tts': 'القراءة الصوتية',
      'ttsOn': 'القراءة الصوتية قيد التشغيل',
      'ttsOff': 'القراءة الصوتية متوقفة',
      'speak_zikr': 'اقرأ الذكر',
      'export': 'تصدير',
      'import': 'استيراد',
      'import_success': 'تم الاستيراد بنجاح!',
      'import_failed': 'فشل الاستيراد',
      'export_success': 'تم التصدير بنجاح!',
      'export_failed': 'فشل التصدير',
      'developer_name': 'Caner Erdem',
      'developer_title': 'المطور',
      'developer_website': 'www.mcanererdem.com',
      'developer_email': 'info@mcanererdem.com',
      'developer_github': 'github.com/mcanererdem',
    },
    'id': {
      'app_name': 'Tasbih Digital',
      'help_title': 'Bantuan Aplikasi',
      'help_streak_title': 'Apa itu Streak?',
      'help_streak_text': 'Saat Anda menyelesaikan target secara rutin, Anda mendapatkan streak. Semakin lama dipertahankan, semakin tinggi motivasi. Selesaikan setidaknya satu target setiap hari agar streak tetap hidup!',
      'help_goal_title': 'Bagaimana Cara Kerja Target?',
      'help_goal_text': 'Anda dapat menetapkan target harian, mingguan, atau bulanan. Misalnya: "1000 dzikir per hari". Saat mencapai target, Anda akan mendapatkan notifikasi dan animasi khusus.',
      'help_addzikr_title': 'Bagaimana Menambah Dzikir?',
      'help_addzikr_text': 'Ketuk nama dzikir di beranda untuk membuka layar pilihan. Pilih dari dzikir yang ada atau buat sendiri dengan tombol "Tambah Dzikir Baru".',
      'help_toggles_title': 'Tombol Toggle',
      'help_toggles_text': 'Gunakan kontrol bawah (Getaran, Suara, Konfeti) untuk menyalakan/mematikan fitur seketika dan personalisasi pengalaman Anda.',
      'enable_reminder': 'Aktifkan Pengingat',
      'reminder_enabled': 'Pengingat aktif',
      'reminder_disabled': 'Pengingat nonaktif',
      'reminder_set_success': 'Pengingat diatur!',
      'reminder_set_fail': 'Tidak dapat mengatur pengingat. Mohon berikan izin.',
      'reminder_cancelled': 'Pengingat dibatalkan.',
      'test_notification_sent': 'Notifikasi uji terkirim!',
      'test': 'Uji',
      'close': 'Tutup',
      'counter': 'Penghitung',
      'target': 'Target',
      'reset': 'Atur Ulang',
      'continue': 'Lanjutkan',
      'cancel': 'Batal',
      'ok': 'OK',
      'settings': 'Pengaturan',
      'theme': 'Tema',
      'language': 'Bahasa',
      'vibration': 'Getaran',
      'sound': 'Suara',
      'select_zikr': 'Pilih Dzikir',
      'add_zikr': 'Tambah Dzikir',
      'custom_zikrs': 'Dzikir Kustom',
      'zikr_name_ar': 'Nama Arab',
      'zikr_name_tr': 'Nama Turki',
      'zikr_name_en': 'Nama Inggris',
      'zikr_name_id': 'Nama Indonesia',
      'zikr_name_ur': 'Nama Urdu',
      'zikr_name_bn': 'Nama Bengali',
      'zikr_name_ms': 'Nama Melayu',
      'zikr_name_fa': 'Nama Persia',
      'zikr_name_fr': 'Nama Prancis',
      'zikr_name_zh': 'Nama Cina',
      'zikr_name_ja': 'Nama Jepang',
      'zikr_name_ru': 'Nama Rusia',
      'zikr_name_de': 'Nama Jerman',
      'zikr_name_sw': 'Nama Swahili',
      'zikr_name_ha': 'Nama Hausa',
      'contact': 'Hubungi',
      'source_code': 'Kode Sumber',
      'default_count': 'Jumlah Default',
      'set_target': 'Atur Target',
      'quick_select': 'Pilihan Cepat',
      'custom_target': 'Target Kustom',
      'enter_target': 'Masukkan nomor target',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Target tercapai!',
      'zikr_count': 'Dzikir',
      'edit': 'Edit',
      'delete': 'Hapus',
      'save': 'Simpan',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Tambah penghitung',
      'resetCounter': 'Atur ulang penghitung',
      'changeTarget': 'Ubah target',
      'vibrationOn': 'Getaran aktif',
      'vibrationOff': 'Getaran nonaktif',
      'soundOn': 'Suara aktif',
      'soundOff': 'Suara nonaktif',
      'about': 'Tentang',
      'confettiOn': 'Konfeti aktif',
      'confettiOff': 'Konfeti nonaktif',
      'setReminder': 'Atur Pengingat',
      'cancelReminder': 'Batal',
      'goals': 'Target',
      'dailyGoal': 'Target Harian',
      'weeklyGoal': 'Target Mingguan',
      'monthlyGoal': 'Target Bulanan',
      'setGoal': 'Atur Target',
      'goalCompleted': 'Target Tercapai! 🎯',
      'progress': 'Kemajuan',
      'statistics': 'Statistik',
      'today': 'Hari Ini',
      'total': 'Total',
      'streak': 'Beruntun',
      'consecutiveDays': 'Hari berturut-turut',
      'last7Days': '7 Hari Terakhir',
      'days': 'hari',
      'mon': 'Sen',
      'tue': 'Sel',
      'wed': 'Rab',
      'thu': 'Kam',
      'fri': 'Jum',
      'sat': 'Sab',
      'sun': 'Min',
      'trophies': 'Trofi',
      'streak_continues': 'beruntun berlanjut',
      'new_record': 'Rekor baru!',
      'achievement_streaks': 'Pencapaian Beruntun',
      'weeks': 'Minggu',
      'months': 'Bulan',
      'last_4_weeks': '4 Minggu Terakhir',
      'last_12_months': '12 Bulan Terakhir',
      'optional': 'Opsional',
      'required': 'diperlukan',
      'transliteration': 'Transliterasi',
      'version': 'Versi 1.0.0',
      'support_us': 'Dukung Kami',
      'support_description': 'Bantu kami menjaga aplikasi ini gratis dengan menonton iklan singkat. Dukungan Anda sangat berarti!',
      'watch_ad': 'Tonton Iklan',
      'ad_not_ready': 'Iklan belum siap, silakan coba lagi',
      'thank_you_support': 'Terima kasih atas dukungan Anda! 🙏',
      'features': 'Fitur',
      'feature_goals': 'Target Harian, Mingguan, Bulanan',
      'feature_statistics': 'Statistik Terperinci',
      'feature_widget': 'Widget Layar Utama',
      'feature_languages': 'Dukungan 15 Bahasa',
      'day_streak': 'Beruntun Harian',
      'new_best': 'Terbaik Baru!',
      'completed_today': 'Selesai Hari Ini',
      'tts': 'Pembacaan Suara',
      'ttsOn': 'Pembacaan suara aktif',
      'ttsOff': 'Pembacaan suara nonaktif',
      'speak_zikr': 'Bacakan Dzikir',
      'export': 'Ekspor',
      'import': 'Impor',
      'import_success': 'Impor berhasil!',
      'import_failed': 'Impor gagal',
      'export_success': 'Ekspor berhasil!',
      'export_failed': 'Ekspor gagal',
    },
    // Urduca (Pakistan, Hindistan)
    'ur': {
      'app_name': 'تسبیح کاؤنٹر',
      'counter': 'کاؤنٹر',
      'target': 'ہدف',
      'reset': 'ریسیٹ',
      'continue': 'جاری رکھیں',
      'cancel': 'منسوخ',
      'ok': 'ٹھیک ہے',
      'settings': 'ترتیبات',
      'theme': 'تھیم',
      'language': 'زبان',
      'vibration': 'تھرتھراہٹ',
      'sound': 'آواز',
      'success_title': 'ماشاء اللہ! 🎉',
      'success_message': 'ہدف حاصل!',
      'goals': 'اہداف',
      'dailyGoal': 'روزانہ ہدف',
      'weeklyGoal': 'ہفتہ وار ہدف',
      'monthlyGoal': 'ماہانہ ہدف',
      'progress': 'پیش رفت',
      'statistics': 'شماریات',
      'today': 'آج',
      'total': 'کل',
      'streak': 'سلسلہ',
      'consecutiveDays': 'مسلسل دن',
      'last7Days': 'آخری 7 دن',
      'days': 'دن',
      'select_zikr': 'ذکر منتخب کریں',
      'add_zikr': 'ذکر شامل کریں',
      'custom_zikrs': 'حسب ضرورت ذکر',
      'zikr_name_ar': 'عربی نام',
      'zikr_name_tr': 'ترکی نام',
      'zikr_name_en': 'انگریزی نام',
      'zikr_name_id': 'انڈونیشیائی نام',
      'zikr_name_ur': 'اردو نام',
      'zikr_name_bn': 'بنگالی نام',
      'zikr_name_ms': 'ملائی نام',
      'zikr_name_fa': 'فارسی نام',
      'zikr_name_fr': 'فرانسیسی نام',
      'zikr_name_zh': 'چینی نام',
      'zikr_name_ja': 'جاپانی نام',
      'zikr_name_ru': 'روسی نام',
      'zikr_name_de': 'جرمن نام',
      'zikr_name_sw': 'سواحیلی نام',
      'zikr_name_ha': 'ہاؤسا نام',
      'default_count': 'ڈیفالٹ تعداد',
      'set_target': 'ہدف مقرر کریں',
      'quick_select': 'فوری انتخاب',
      'custom_target': 'حسب ضرورت ہدف',
      'enter_target': 'ہدف نمبر درج کریں',
      'setGoal': 'ہدف مقرر کریں',
      'goalCompleted': 'ہدف مکمل! 🎯',
      'zikr_count': 'ذکر',
      'edit': 'ترمیم',
      'delete': 'حذف کریں',
      'save': 'محفوظ کریں',
      'trophies': 'انعامات',
      'streak_continues': 'سلسلہ جاری',
      'new_record': 'نیا ریکارڈ!',
      'achievement_streaks': 'کامیابی کے سلسلے',
      'weeks': 'ہفتے',
      'months': 'مہینے',
      'last_4_weeks': 'آخری 4 ہفتے',
      'last_12_months': 'آخری 12 مہینے',
      'optional': 'اختیاری',
      'required': 'ضروری',
      'transliteration': 'نقل حرفی',
      'version': 'ورژن 1.0.0',
      'support_us': 'ہماری مدد کریں',
      'support_description': 'ایک مختصر اشتہار دیکھ کر اس ایپ کو مفت رکھنے میں ہماری مدد کریں۔ آپ کی حمایت بہت اہمیت رکھتی ہے!',
      'watch_ad': 'اشتہار دیکھیں',
      'ad_not_ready': 'اشتہار تیار نہیں، براہ کرم دوبارہ کوشش کریں',
      'thank_you_support': 'آپ کی حمایت کا شکریہ! 🙏',
      'features': 'خصوصیات',
      'feature_goals': 'روزانہ، ہفتہ وار، ماہانہ اہداف',
      'feature_statistics': 'تفصیلی شماریات',
      'feature_widget': 'ہوم اسکرین ویجٹ',
      'feature_languages': '15 زبانوں کی معاونت',
          'contact': 'رابطہ',
      'source_code': 'سورس کوڈ',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'کاؤنٹر بڑھائیں',
      'resetCounter': 'کاؤنٹر ریسیٹ کریں',
      'changeTarget': 'ہدف تبدیل کریں',
      'vibrationOn': 'تھرتھراہٹ چالو',
      'vibrationOff': 'تھرتھراہٹ بند',
      'soundOn': 'آواز چالو',
      'soundOff': 'آواز بند',
      'about': 'تعارف',
      'confettiOn': 'کنفیٹی چالو',
      'confettiOff': 'کنفیٹی بند',
      'setReminder': 'یاد دہانی ترتیب دیں',
      'cancelReminder': 'منسوخ',
      'mon': 'پیر',
      'tue': 'منگل',
      'wed': 'بدھ',
      'thu': 'جمعرات',
      'fri': 'جمعہ',
      'sat': 'ہفتہ',
      'sun': 'اتوار',
      'day_streak': 'یومیہ سلسلہ',
      'new_best': 'نئی بہترین!',
      'completed_today': 'آج مکمل',
      'tts': 'آواز پڑھنا',
      'ttsOn': 'آواز پڑھنا چالو',
      'ttsOff': 'آواز پڑھنا بند',
      'speak_zikr': 'ذکر پڑھیں',
      'export': 'برآمد',
      'import': 'درآمد',
      'import_success': 'درآمد کامیاب!',
      'import_failed': 'درآمد ناکام',
      'export_success': 'برآمد کامیاب!',
      'export_failed': 'برآمد ناکام',
},
    // Bengalce (Bangladeş)
    'bn': {
      'app_name': 'তসবিহ কাউন্টার',
      'counter': 'কাউন্টার',
      'target': 'লক্ষ্য',
      'reset': 'রিসেট',
      'continue': 'চালিয়ে যান',
      'cancel': 'বাতিল',
      'ok': 'ঠিক আছে',
      'settings': 'সেটিংস',
      'theme': 'থিম',
      'language': 'ভাষা',
      'vibration': 'কম্পন',
      'sound': 'শব্দ',
      'success_title': 'মাশাআল্লাহ! 🎉',
      'success_message': 'লক্ষ্য পৌঁছেছে!',
      'goals': 'লক্ষ্য',
      'dailyGoal': 'দৈনিক লক্ষ্য',
      'weeklyGoal': 'সাপ্তাহিক লক্ষ্য',
      'monthlyGoal': 'মাসিক লক্ষ্য',
      'progress': 'অগ্রগতি',
      'statistics': 'পরিসংখ্যান',
      'today': 'আজ',
      'total': 'মোট',
      'streak': 'ধারা',
      'consecutiveDays': 'পরপর দিন',
      'last7Days': 'শেষ ৭ দিন',
      'days': 'দিন',
      'select_zikr': 'জিকির নির্বাচন করুন',
      'add_zikr': 'জিকির যোগ করুন',
      'custom_zikrs': 'কাস্টম জিকির',
      'zikr_name_ar': 'আরবি নাম',
      'zikr_name_tr': 'তুর্কি নাম',
      'zikr_name_en': 'ইংরেজি নাম',
      'zikr_name_id': 'ইন্দোনেশীয় নাম',
      'zikr_name_ur': 'উর্দু নাম',
      'zikr_name_bn': 'বাংলা নাম',
      'zikr_name_ms': 'মালয় নাম',
      'zikr_name_fa': 'ফার্সি নাম',
      'zikr_name_fr': 'ফরাসি নাম',
      'zikr_name_zh': 'চীনা নাম',
      'zikr_name_ja': 'জাপানি নাম',
      'zikr_name_ru': 'রাশিয়ান নাম',
      'zikr_name_de': 'জার্মান নাম',
      'zikr_name_sw': 'সোয়াহিলি নাম',
      'zikr_name_ha': 'হাউসা নাম',
      'default_count': 'ডিফল্ট সংখ্যা',
      'set_target': 'লক্ষ্য নির্ধারণ করুন',
      'quick_select': 'দ্রুত নির্বাচন',
      'custom_target': 'কাস্টম লক্ষ্য',
      'enter_target': 'লক্ষ্য সংখ্যা লিখুন',
      'setGoal': 'লক্ষ্য নির্ধারণ',
      'goalCompleted': 'লক্ষ্য সম্পন্ন! 🎯',
      'zikr_count': 'জিকির',
      'edit': 'সম্পাদনা',
      'delete': 'মুছুন',
      'save': 'সংরক্ষণ',
      'trophies': 'ট্রফি',
      'streak_continues': 'ধারা অব্যাহত',
      'new_record': 'নতুন রেকর্ড!',
      'achievement_streaks': 'অর্জন ধারা',
      'weeks': 'সপ্তাহ',
      'months': 'মাস',
      'last_4_weeks': 'শেষ ৪ সপ্তাহ',
      'last_12_months': 'শেষ ১২ মাস',
      'optional': 'ঐচ্ছিক',
      'required': 'প্রয়োজনীয়',
      'transliteration': 'প্রতিবর্ণীকরণ',
      'version': 'সংস্করণ 1.0.0',
      'support_us': 'আমাদের সমর্থন করুন',
      'support_description': 'একটি সংক্ষিপ্ত বিজ্ঞাপন দেখে এই অ্যাপটি বিনামূল্যে রাখতে আমাদের সাহায্য করুন। আপনার সমর্থন অনেক গুরুত্বপূর্ণ!',
      'watch_ad': 'বিজ্ঞাপন দেখুন',
      'ad_not_ready': 'বিজ্ঞাপন প্রস্তুত নয়, অনুগ্রহ করে আবার চেষ্টা করুন',
      'thank_you_support': 'আপনার সমর্থনের জন্য ধন্যবাদ! 🙏',
      'features': 'বৈশিষ্ট্য',
      'feature_goals': 'দৈনিক, সাপ্তাহিক, মাসিক লক্ষ্য',
      'feature_statistics': 'বিস্তারিত পরিসংখ্যান',
      'feature_widget': 'হোম স্ক্রিন উইজেট',
      'feature_languages': '১৫টি ভাষার সমর্থন',
          'contact': 'যোগাযোগ',
      'source_code': 'সোর্স কোড',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'কাউন্টার বাড়ান',
      'resetCounter': 'কাউন্টার রিসেট করুন',
      'changeTarget': 'লক্ষ্য পরিবর্তন করুন',
      'vibrationOn': 'কম্পন চালু',
      'vibrationOff': 'কম্পন বন্ধ',
      'soundOn': 'শব্দ চালু',
      'soundOff': 'শব্দ বন্ধ',
      'about': 'সম্পর্কে',
      'confettiOn': 'কনফেটি চালু',
      'confettiOff': 'কনফেটি বন্ধ',
      'setReminder': 'অনুস্মারক সেট করুন',
      'cancelReminder': 'বাতিল',
      'mon': 'সোম',
      'tue': 'মঙ্গল',
      'wed': 'বুধ',
      'thu': 'বৃহঃ',
      'fri': 'শুক্র',
      'sat': 'শনি',
      'sun': 'রবি',
      'day_streak': 'দৈনিক ধারা',
      'new_best': 'নতুন সেরা!',
      'completed_today': 'আজ সম্পন্ন',
      'tts': 'ভয়েস পাঠ',
      'ttsOn': 'ভয়েস পাঠ চালু',
      'ttsOff': 'ভয়েস পাঠ বন্ধ',
      'speak_zikr': 'জিকির পড়ুন',
      'export': 'রপ্তানি',
      'import': 'আমদানি',
      'import_success': 'আমদানি সফল!',
      'import_failed': 'আমদানি ব্যর্থ',
      'export_success': 'রপ্তানি সফল!',
      'export_failed': 'রপ্তানি ব্যর্থ',
},
    // Malayca (Malezya)
    'ms': {
      'app_name': 'Kaunter Tasbih',
      'counter': 'Kaunter',
      'target': 'Sasaran',
      'reset': 'Set Semula',
      'continue': 'Teruskan',
      'cancel': 'Batal',
      'ok': 'OK',
      'settings': 'Tetapan',
      'theme': 'Tema',
      'language': 'Bahasa',
      'vibration': 'Getaran',
      'sound': 'Bunyi',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Sasaran tercapai!',
      'goals': 'Matlamat',
      'dailyGoal': 'Matlamat Harian',
      'weeklyGoal': 'Matlamat Mingguan',
      'monthlyGoal': 'Matlamat Bulanan',
      'progress': 'Kemajuan',
      'statistics': 'Statistik',
      'today': 'Hari Ini',
      'total': 'Jumlah',
      'streak': 'Berturut-turut',
      'consecutiveDays': 'Hari berturut-turut',
      'last7Days': '7 Hari Terakhir',
      'days': 'hari',
      'select_zikr': 'Pilih Zikir',
      'add_zikr': 'Tambah Zikir',
      'custom_zikrs': 'Zikir Tersuai',
      'zikr_name_ar': 'Nama Arab',
      'zikr_name_tr': 'Nama Turki',
      'zikr_name_en': 'Nama Inggeris',
      'zikr_name_id': 'Nama Indonesia',
      'zikr_name_ur': 'Nama Urdu',
      'zikr_name_bn': 'Nama Bengali',
      'zikr_name_ms': 'Nama Melayu',
      'zikr_name_fa': 'Nama Parsi',
      'zikr_name_fr': 'Nama Perancis',
      'zikr_name_zh': 'Nama Cina',
      'zikr_name_ja': 'Nama Jepun',
      'zikr_name_ru': 'Nama Rusia',
      'zikr_name_de': 'Nama Jerman',
      'zikr_name_sw': 'Nama Swahili',
      'zikr_name_ha': 'Nama Hausa',
      'default_count': 'Kiraan Lalai',
      'set_target': 'Tetapkan Sasaran',
      'quick_select': 'Pilihan Pantas',
      'custom_target': 'Sasaran Tersuai',
      'enter_target': 'Masukkan nombor sasaran',
      'setGoal': 'Tetapkan Matlamat',
      'goalCompleted': 'Matlamat Tercapai! 🎯',
      'zikr_count': 'Zikir',
      'edit': 'Edit',
      'delete': 'Padam',
      'save': 'Simpan',
      'trophies': 'Trofi',
      'streak_continues': 'berturut-turut berterusan',
      'new_record': 'Rekod baharu!',
      'achievement_streaks': 'Pencapaian Berturut-turut',
      'weeks': 'Minggu',
      'months': 'Bulan',
      'last_4_weeks': '4 Minggu Terakhir',
      'last_12_months': '12 Bulan Terakhir',
      'optional': 'Pilihan',
      'required': 'diperlukan',
      'transliteration': 'Transliterasi',
      'version': 'Versi 1.0.0',
      'support_us': 'Sokong Kami',
      'support_description': 'Bantu kami mengekalkan aplikasi ini percuma dengan menonton iklan pendek. Sokongan anda sangat bermakna!',
      'watch_ad': 'Tonton Iklan',
      'ad_not_ready': 'Iklan belum sedia, sila cuba lagi',
      'thank_you_support': 'Terima kasih atas sokongan anda! 🙏',
      'features': 'Ciri-ciri',
      'feature_goals': 'Matlamat Harian, Mingguan, Bulanan',
      'feature_statistics': 'Statistik Terperinci',
      'feature_widget': 'Widget Skrin Utama',
      'feature_languages': 'Sokongan 15 Bahasa',
          'contact': 'Hubungi',
      'source_code': 'Kod Sumber',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Tambah kaunter',
      'resetCounter': 'Set semula kaunter',
      'changeTarget': 'Tukar sasaran',
      'vibrationOn': 'Getaran hidup',
      'vibrationOff': 'Getaran mati',
      'soundOn': 'Bunyi hidup',
      'soundOff': 'Bunyi mati',
      'about': 'Perihal',
      'confettiOn': 'Konfeti hidup',
      'confettiOff': 'Konfeti mati',
      'setReminder': 'Tetapkan Peringatan',
      'cancelReminder': 'Batal',
      'mon': 'Isn',
      'tue': 'Sel',
      'wed': 'Rab',
      'thu': 'Kha',
      'fri': 'Jum',
      'sat': 'Sab',
      'sun': 'Ahd',
      'day_streak': 'Siri Harian',
      'new_best': 'Terbaik Baharu!',
      'completed_today': 'Selesai Hari Ini',
      'tts': 'Bacaan Suara',
      'ttsOn': 'Bacaan suara hidup',
      'ttsOff': 'Bacaan suara mati',
      'speak_zikr': 'Baca Zikir',
      'export': 'Eksport',
      'import': 'Import',
      'import_success': 'Import berjaya!',
      'import_failed': 'Import gagal',
      'export_success': 'Eksport berjaya!',
      'export_failed': 'Eksport gagal',
},
    // Farsça (İran)
    'fa': {
      'app_name': 'شمارنده تسبیح',
      'help_title': 'راهنمای برنامه',
      'help_streak_title': 'Streak چیست؟',
      'help_streak_text': 'با تکمیل منظم اهداف، یک رشته (Streak) کسب می‌کنید. هرچه بیشتر آن را حفظ کنید، انگیزه بیشتری خواهید داشت. هر روز حداقل یک هدف را تکمیل کنید!',
      'help_goal_title': 'اهداف چگونه کار می‌کنند؟',
      'help_goal_text': 'می‌توانید اهداف روزانه، هفتگی یا ماهانه تعیین کنید. برای مثال: "1000 ذکر در روز". هنگام رسیدن به اهداف، اعلان‌ها و انیمیشن‌های ویژه دریافت می‌کنید.',
      'help_addzikr_title': 'چگونه ذکر اضافه کنم؟',
      'help_addzikr_text': 'روی نام ذکر در صفحه اصلی بزنید تا صفحه انتخاب باز شود. از اذکار موجود انتخاب کنید یا با دکمه "افزودن ذکر جدید" ذکر خود را بسازید.',
      'help_toggles_title': 'دکمه‌های تغییر وضعیت',
      'help_toggles_text': 'از کنترل‌های پایین (لرزش، صدا، کنفتی) برای روشن/خاموش کردن فوری ویژگی‌ها و شخصی‌سازی تجربه استفاده کنید.',
      'enable_reminder': 'فعال‌سازی یادآور',
      'reminder_set_success': 'یادآور تنظیم شد!',
      'reminder_set_fail': 'تنظیم یادآور ممکن نشد. لطفاً مجوزها را بدهید.',
      'reminder_cancelled': 'یادآور لغو شد.',
      'test_notification_sent': 'اعلان آزمایشی ارسال شد!',
      'test': 'آزمایش',
      'close': 'بستن',
      'counter': 'شمارنده',
      'target': 'هدف',
      'reset': 'بازنشانی',
      'continue': 'ادامه',
      'cancel': 'لغو',
      'ok': 'تأیید',
      'settings': 'تنظیمات',
      'theme': 'تم',
      'language': 'زبان',
      'vibration': 'لرزش',
      'sound': 'صدا',
      'success_title': 'ماشاءالله! 🎉',
      'success_message': 'به هدف رسیدید!',
      'goals': 'اهداف',
      'dailyGoal': 'هدف روزانه',
      'weeklyGoal': 'هدف هفتگی',
      'monthlyGoal': 'هدف ماهانه',
      'progress': 'پیشرفت',
      'statistics': 'آمار',
      'today': 'امروز',
      'total': 'کل',
      'streak': 'رشته',
      'consecutiveDays': 'روزهای متوالی',
      'last7Days': '7 روز گذشته',
      'days': 'روز',
      'select_zikr': 'انتخاب ذکر',
      'add_zikr': 'افزودن ذکر',
      'custom_zikrs': 'ذکرهای سفارشی',
      'zikr_name_ar': 'نام عربی',
      'zikr_name_tr': 'نام ترکی',
      'zikr_name_en': 'نام انگلیسی',
      'default_count': 'تعداد پیش‌فرض',
      'set_target': 'تعیین هدف',
      'quick_select': 'انتخاب سریع',
      'custom_target': 'هدف سفارشی',
      'enter_target': 'شماره هدف را وارد کنید',
      'setGoal': 'تعیین هدف',
      'goalCompleted': 'هدف تکمیل شد! 🎯',
      'zikr_count': 'ذکر',
      'edit': 'ویرایش',
      'delete': 'حذف',
      'save': 'ذخیره',
      'trophies': 'جوایز',
      'streak_continues': 'رشته ادامه دارد',
      'new_record': 'رکورد جدید!',
      'achievement_streaks': 'رشتههای موفقیت',
      'weeks': 'هفته',
      'months': 'ماه',
      'last_4_weeks': '4 هفته گذشته',
      'last_12_months': '12 ماه گذشته',
      'optional': 'اختیاری',
      'required': 'ضروری',
      'transliteration': 'نویسه‌گردانی',
      'version': 'نسخه 1.0.0',
      'support_us': 'از ما حمایت کنید',
      'support_description': 'با تماشای یک تبلیغ کوتاه به ما کمک کنید این برنامه را رایگان نگه داریم. حمایت شما بسیار ارزشمند است!',
      'watch_ad': 'تماشای تبلیغ',
      'ad_not_ready': 'تبلیغ آماده نیست، لطفاً دوباره امتحان کنید',
      'thank_you_support': 'از حمایت شما متشکریم! 🙏',
      'features': 'ویژگی‌ها',
      'feature_goals': 'اهداف روزانه، هفتگی، ماهانه',
      'feature_statistics': 'آمار تفصیلی',
      'feature_widget': 'ویجت صفحه اصلی',
      'feature_languages': 'پشتیبانی از 15 زبان',
          'zikr_name_id': 'نام اندونزیایی',
      'zikr_name_ur': 'نام اردو',
      'zikr_name_bn': 'نام بنگالی',
      'zikr_name_ms': 'نام مالایی',
      'zikr_name_fa': 'نام فارسی',
      'zikr_name_fr': 'نام فرانسوی',
      'zikr_name_zh': 'نام چینی',
      'zikr_name_ja': 'نام ژاپنی',
      'zikr_name_ru': 'نام روسی',
      'zikr_name_de': 'نام آلمانی',
      'zikr_name_sw': 'نام سواحیلی',
      'zikr_name_ha': 'نام هاوسا',
      'contact': 'تماس',
      'source_code': 'کد منبع',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'افزایش شمارنده',
      'resetCounter': 'بازنشانی شمارنده',
      'changeTarget': 'تغییر هدف',
      'vibrationOn': 'لرزش روشن',
      'vibrationOff': 'لرزش خاموش',
      'soundOn': 'صدا روشن',
      'soundOff': 'صدا خاموش',
      'about': 'درباره',
      'confettiOn': 'کنفتی روشن',
      'confettiOff': 'کنفتی خاموش',
      'setReminder': 'تنظیم یادآور',
      'cancelReminder': 'لغو',
      'mon': 'دوشنبه',
      'tue': 'سه‌شنبه',
      'wed': 'چهارشنبه',
      'thu': 'پنج‌شنبه',
      'fri': 'جمعه',
      'sat': 'شنبه',
      'sun': 'یکشنبه',
      'day_streak': 'سری روزانه',
      'new_best': 'بهترین جدید!',
      'completed_today': 'امروز تکمیل شد',
      'tts': 'خواندن صوتی',
      'ttsOn': 'خواندن صوتی روشن',
      'ttsOff': 'خواندن صوتی خاموش',
      'speak_zikr': 'ذکر بخوانید',
      'export': 'صادر کردن',
      'import': 'وارد کردن',
      'import_success': 'وارد کردن موفق!',
      'import_failed': 'وارد کردن ناموفق',
      'export_success': 'صادر کردن موفق!',
      'export_failed': 'صادر کردن ناموفق',
},
    // Fransızca (Kuzey Afrika)
    'fr': {
      'app_name': 'Compteur Tasbih',
      'help_title': "Aide de l'application",
      'help_streak_title': 'Qu’est-ce qu’une série (Streak) ?',
      'help_streak_text': 'Lorsque vous complétez vos objectifs régulièrement, vous obtenez une série. Plus vous la maintenez, plus votre motivation augmente. Complétez au moins un objectif par jour pour la garder active !',
      'help_goal_title': 'Comment fonctionnent les objectifs ?',
      'help_goal_text': 'Vous pouvez définir des objectifs quotidiens, hebdomadaires ou mensuels. Par exemple : "1000 dhikr par jour". À l’atteinte, vous recevez des notifications et animations spéciales.',
      'help_addzikr_title': 'Comment ajouter un Dhikr ?',
      'help_addzikr_text': 'Touchez le nom du dhikr sur l’écran d’accueil pour ouvrir la sélection. Choisissez un dhikr existant ou créez le vôtre via "Ajouter un nouveau Dhikr".',
      'help_toggles_title': 'Boutons de bascule',
      'help_toggles_text': 'Utilisez les contrôles du bas (Vibration, Son, Confettis) pour activer/désactiver instantanément et personnaliser votre expérience.',
      'enable_reminder': 'Activer le rappel',
      'reminder_enabled': 'Rappel actif',
      'reminder_disabled': 'Rappel inactif',
      'reminder_set_success': 'Rappel réglé !',
      'reminder_set_fail': 'Impossible de régler le rappel. Veuillez accorder les autorisations.',
      'reminder_cancelled': 'Rappel annulé.',
      'test_notification_sent': 'Notification de test envoyée !',
      'test': 'Test',
      'close': 'Fermer',
      'counter': 'Compteur',
      'target': 'Objectif',
      'reset': 'Réinitialiser',
      'continue': 'Continuer',
      'cancel': 'Annuler',
      'ok': 'OK',
      'settings': 'Paramètres',
      'theme': 'Thème',
      'language': 'Langue',
      'vibration': 'Vibration',
      'sound': 'Son',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Objectif atteint!',
      'goals': 'Objectifs',
      'dailyGoal': 'Objectif Quotidien',
      'weeklyGoal': 'Objectif Hebdomadaire',
      'monthlyGoal': 'Objectif Mensuel',
      'progress': 'Progrès',
      'statistics': 'Statistiques',
      'today': "Aujourd'hui",
      'total': 'Total',
      'streak': 'Série',
      'consecutiveDays': 'Jours consécutifs',
      'last7Days': '7 Derniers Jours',
      'days': 'jours',
      'select_zikr': 'Sélectionner Dhikr',
      'add_zikr': 'Ajouter Dhikr',
      'custom_zikrs': 'Dhikrs Personnalisés',
      'zikr_name_ar': 'Nom Arabe',
      'zikr_name_tr': 'Nom Turc',
      'zikr_name_en': 'Nom Anglais',
      'zikr_name_id': 'Nom Indonésien',
      'zikr_name_ur': 'Nom Ourdou',
      'zikr_name_bn': 'Nom Bengali',
      'zikr_name_ms': 'Nom Malais',
      'zikr_name_fa': 'Nom Persan',
      'zikr_name_fr': 'Nom Français',
      'zikr_name_zh': 'Nom Chinois',
      'zikr_name_ja': 'Nom Japonais',
      'zikr_name_ru': 'Nom Russe',
      'zikr_name_de': 'Nom Allemand',
      'zikr_name_sw': 'Nom Swahili',
      'zikr_name_ha': 'Nom Haoussa',
      'set_target': 'Définir Objectif',
      'quick_select': 'Sélection Rapide',
      'custom_target': 'Objectif Personnalisé',
      'enter_target': 'Entrez le numéro cible',
      'setGoal': 'Définir Objectif',
      'goalCompleted': 'Objectif Atteint! 🎯',
      'zikr_count': 'Dhikr',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'save': 'Enregistrer',
      'trophies': 'Trophées',
      'streak_continues': 'série continue',
      'new_record': 'Nouveau record!',
      'achievement_streaks': 'Séries de Réussite',
      'weeks': 'Semaines',
      'months': 'Mois',
      'last_4_weeks': '4 Dernières Semaines',
      'last_12_months': '12 Derniers Mois',
      'optional': 'Optionnel',
      'required': 'requis',
      'transliteration': 'Translittération',
      'version': 'Version 1.0.0',
      'support_us': 'Soutenez-nous',
      'support_description': 'Aidez-nous à garder cette application gratuite en regardant une courte publicité. Votre soutien compte beaucoup!',
      'watch_ad': 'Regarder la Publicité',
      'ad_not_ready': 'Publicité non prête, veuillez réessayer',
      'thank_you_support': 'Merci pour votre soutien! 🙏',
      'features': 'Fonctionnalités',
      'feature_goals': 'Objectifs Quotidiens, Hebdomadaires, Mensuels',
      'feature_statistics': 'Statistiques Détaillées',
      'feature_widget': 'Widget Écran d\'Accueil',
      'feature_languages': 'Support de 15 Langues',
          'contact': 'Contact',
      'source_code': 'Code Source',
      'default_count': 'Nombre par Défaut',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Incrémenter le compteur',
      'resetCounter': 'Réinitialiser le compteur',
      'changeTarget': 'Changer l\'objectif',
      'vibrationOn': 'Vibration activée',
      'vibrationOff': 'Vibration désactivée',
      'soundOn': 'Son activé',
      'soundOff': 'Son désactivé',
      'about': 'À propos',
      'confettiOn': 'Confettis activés',
      'confettiOff': 'Confettis désactivés',
      'setReminder': 'Définir un rappel',
      'cancelReminder': 'Annuler',
      'today': 'Aujourd\'hui',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mer',
      'thu': 'Jeu',
      'fri': 'Ven',
      'sat': 'Sam',
      'sun': 'Dim',
      'day_streak': 'Série Quotidienne',
      'new_best': 'Nouveau Record!',
      'completed_today': 'Complété Aujourd\'hui',
      'tts': 'Lecture Vocale',
      'ttsOn': 'Lecture vocale activée',
      'ttsOff': 'Lecture vocale désactivée',
      'speak_zikr': 'Lire le Dhikr',
      'export': 'Exporter',
      'import': 'Importer',
      'import_success': 'Importation réussie!',
      'import_failed': 'Importation échouée',
      'export_success': 'Exportation réussie!',
      'export_failed': 'Exportation échouée',
},
    // Çince (Çin)
    'zh': {
      'app_name': '计数器',
      'help_title': '应用帮助',
      'help_streak_title': '什么是连续（Streak）？',
      'help_streak_text': '当你经常完成目标时，你会获得连续。连续保持越久，动力越强。每天至少完成一个目标以保持连续！',
      'help_goal_title': '目标如何工作？',
      'help_goal_text': '你可以设置每日、每周或每月目标。例如：“每天1000次念诵”。达到目标时会收到特别通知和动画。',
      'help_addzikr_title': '如何添加念诵？',
      'help_addzikr_text': '在主屏点击念诵名称打开选择界面。从现有念诵中选择或通过“添加新念诵”创建。',
      'help_toggles_title': '切换按钮',
      'help_toggles_text': '使用底部的控制（震动、声音、彩纸）即时切换功能并个性化体验。',
      'enable_reminder': '启用提醒',
      'reminder_enabled': '提醒已启用',
      'reminder_disabled': '提醒未启用',
      'reminder_set_success': '提醒已设置！',
      'reminder_set_fail': '无法设置提醒。请授予权限。',
      'reminder_cancelled': '提醒已取消。',
      'test_notification_sent': '测试通知已发送！',
      'test': '测试',
      'close': '关闭',
      'counter': '计数器',
      'target': '目标',
      'reset': '重置',
      'continue': '继续',
      'cancel': '取消',
      'ok': '确定',
      'settings': '设置',
      'theme': '主题',
      'language': '语言',
      'vibration': '震动',
      'sound': '声音',
      'success_title': '太棒了! 🎉',
      'success_message': '目标达成!',
      'goals': '目标',
      'dailyGoal': '每日目标',
      'weeklyGoal': '每周目标',
      'monthlyGoal': '每月目标',
      'progress': '进度',
      'statistics': '统计',
      'today': '今天',
      'total': '总计',
      'streak': '连续',
      'consecutiveDays': '连续天数',
      'last7Days': '最近7天',
      'days': '天',
      'select_zikr': '选择念诵',
      'add_zikr': '添加念诵',
      'custom_zikrs': '自定义念诵',
      'zikr_name_ar': '阿拉伯名称',
      'zikr_name_tr': '土耳其名称',
      'zikr_name_en': '英文名称',
      'zikr_name_id': '印尼名称',
      'zikr_name_ur': '乌尔都名称',
      'zikr_name_bn': '孟加拉名称',
      'zikr_name_ms': '马来名称',
      'zikr_name_fa': '波斯名称',
      'zikr_name_fr': '法语名称',
      'zikr_name_zh': '中文名称',
      'zikr_name_ja': '日语名称',
      'zikr_name_ru': '俄语名称',
      'zikr_name_de': '德语名称',
      'zikr_name_sw': '斯瓦希里名称',
      'zikr_name_ha': '豪萨名称',
      'set_target': '设定目标',
      'quick_select': '快速选择',
      'custom_target': '自定义目标',
      'enter_target': '输入目标数字',
      'setGoal': '设定目标',
      'goalCompleted': '目标完成！🎯',
      'zikr_count': '念诵',
      'edit': '编辑',
      'delete': '删除',
      'save': '保存',
      'trophies': '奖杯',
      'streak_continues': '连续继续',
      'new_record': '新纪录！',
      'achievement_streaks': '成就连续',
      'weeks': '周',
      'months': '月',
      'last_4_weeks': '最近4周',
      'last_12_months': '最近12个月',
      'optional': '可选',
      'required': '必需',
      'transliteration': '音译',
      'version': '版本 1.0.0',
      'support_us': '支持我们',
      'support_description': '通过观看短广告帮助我们保持此应用免费。您的支持意义重大!',
      'watch_ad': '观看广告',
      'ad_not_ready': '广告未准备好，请重试',
      'thank_you_support': '感谢您的支持! 🙏',
      'features': '功能',
      'feature_goals': '每日、每周、每月目标',
      'feature_statistics': '详细统计',
      'feature_widget': '主屏幕小部件',
      'feature_languages': '支持15种语言',
          'contact': '联系我们',
      'source_code': '源代码',
      'default_count': '默认数量',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': '增加计数',
      'resetCounter': '重置计数',
      'changeTarget': '更改目标',
      'vibrationOn': '振动开启',
      'vibrationOff': '振动关闭',
      'soundOn': '声音开启',
      'soundOff': '声音关闭',
      'about': '关于',
      'confettiOn': '彩纸开启',
      'confettiOff': '彩纸关闭',
      'setReminder': '设置提醒',
      'cancelReminder': '取消',
      'mon': '周一',
      'tue': '周二',
      'wed': '周三',
      'thu': '周四',
      'fri': '周五',
      'sat': '周六',
      'sun': '周日',
      'day_streak': '每日连续',
      'new_best': '新最佳!',
      'completed_today': '今日完成',
      'tts': '语音朗读',
      'ttsOn': '语音朗读开启',
      'ttsOff': '语音朗读关闭',
      'speak_zikr': '朗读念诵',
      'export': '导出',
      'import': '导入',
      'import_success': '导入成功!',
      'import_failed': '导入失败',
      'export_success': '导出成功!',
      'export_failed': '导出失败',
},
    // Japonca (Japonya)
    'ja': {
      'app_name': 'カウンター',
      'help_title': 'アプリのヘルプ',
      'help_streak_title': '連続 (Streak) とは？',
      'help_streak_text': '目標を定期的に達成すると連続が獲得できます。長く維持するほどモチベーションが上がります。毎日少なくとも1つの目標を達成しましょう。',
      'help_goal_title': '目標はどう機能しますか？',
      'help_goal_text': '毎日・毎週・毎月の目標を設定できます。例：「1日に1000回のズィクル」。達成すると特別な通知とアニメーションで報酬が得られます。',
      'help_addzikr_title': 'ズィクルを追加するには？',
      'help_addzikr_text': 'ホーム画面のズィクル名をタップして選択画面を開きます。既存から選ぶか「新しいズィクルを追加」で作成します。',
      'help_toggles_title': 'トグルボタン',
      'help_toggles_text': '下部のコントロール（振動・音・コンフェッティ）で即座に切り替え、体験をパーソナライズします。',
      'enable_reminder': 'リマインダーを有効化',
      'reminder_enabled': 'リマインダー有効',
      'reminder_disabled': 'リマインダー無効',
      'reminder_set_success': 'リマインダーを設定しました！',
      'reminder_set_fail': 'リマインダーを設定できません。許可を与えてください。',
      'reminder_cancelled': 'リマインダーをキャンセルしました。',
      'test_notification_sent': 'テスト通知を送信しました！',
      'test': 'テスト',
      'close': '閉じる',
      'counter': 'カウンター',
      'target': '目標',
      'reset': 'リセット',
      'continue': '続ける',
      'cancel': 'キャンセル',
      'ok': 'OK',
      'settings': '設定',
      'theme': 'テーマ',
      'language': '言語',
      'vibration': '振動',
      'sound': '音',
      'success_title': '素晴らしい! 🎉',
      'success_message': '目標達成!',
      'goals': '目標',
      'dailyGoal': '毎日の目標',
      'weeklyGoal': '毎週の目標',
      'monthlyGoal': '毎月の目標',
      'progress': '進捗',
      'statistics': '統計',
      'today': '今日',
      'total': '合計',
      'streak': '連続',
      'consecutiveDays': '連続日数',
      'last7Days': '過去7日間',
      'days': '日',
      'select_zikr': 'ズィクルを選択',
      'add_zikr': 'ズィクルを追加',
      'custom_zikrs': 'カスタムズィクル',
      'zikr_name_ar': 'アラビア語名',
      'zikr_name_tr': 'トルコ語名',
      'zikr_name_en': '英語名',
      'zikr_name_id': 'インドネシア語名',
      'zikr_name_ur': 'ウルドゥー語名',
      'zikr_name_bn': 'ベンガル語名',
      'zikr_name_ms': 'マレー語名',
      'zikr_name_fa': 'ペルシア語名',
      'zikr_name_fr': 'フランス語名',
      'zikr_name_zh': '中国語名',
      'zikr_name_ja': '日本語名',
      'zikr_name_ru': 'ロシア語名',
      'zikr_name_de': 'ドイツ語名',
      'zikr_name_sw': 'スワヒリ語名',
      'zikr_name_ha': 'ハウサ語名',
      'set_target': '目標を設定',
      'quick_select': 'クイック選択',
      'custom_target': 'カスタム目標',
      'enter_target': '目標番号を入力',
      'setGoal': '目標を設定',
      'goalCompleted': '目標達成！🎯',
      'zikr_count': 'ズィクル',
      'edit': '編集',
      'delete': '削除',
      'save': '保存',
      'trophies': 'トロフィー',
      'streak_continues': '連続継続',
      'new_record': '新記録！',
      'achievement_streaks': '達成連続',
      'weeks': '週',
      'months': '月',
      'last_4_weeks': '過去4週間',
      'last_12_months': '過去12ヶ月',
      'optional': 'オプション',
      'required': '必須',
      'transliteration': '音訳',
      'version': 'バージョン 1.0.0',
      'support_us': 'サポート',
      'support_description': '短い広告を視聴して、このアプリを無料で維持するのを手伝ってください。あなたのサポートは大きな意味があります!',
      'watch_ad': '広告を見る',
      'ad_not_ready': '広告の準備ができていません。もう一度お試しください',
      'thank_you_support': 'ご支援ありがとうございます! 🙏',
      'features': '機能',
      'feature_goals': '毎日、毎週、毎月の目標',
      'feature_statistics': '詳細な統計',
      'feature_widget': 'ホーム画面ウィジェット',
      'feature_languages': '15言語サポート',
          'contact': 'お問い合わせ',
      'source_code': 'ソースコード',
      'default_count': 'デフォルト数',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'カウンターを増やす',
      'resetCounter': 'カウンターをリセット',
      'changeTarget': '目標を変更',
      'vibrationOn': '振動オン',
      'vibrationOff': '振動オフ',
      'soundOn': '音オン',
      'soundOff': '音オフ',
      'about': 'について',
      'confettiOn': 'コンフェティオン',
      'confettiOff': 'コンフェティオフ',
      'setReminder': 'リマインダー設定',
      'cancelReminder': 'キャンセル',
      'mon': '月',
      'tue': '火',
      'wed': '水',
      'thu': '木',
      'fri': '金',
      'sat': '土',
      'sun': '日',
      'day_streak': '毎日の連続',
      'new_best': '新記録!',
      'completed_today': '今日完了',
      'tts': '音声読み上げ',
      'ttsOn': '音声読み上げオン',
      'ttsOff': '音声読み上げオフ',
      'speak_zikr': 'ズィクルを読む',
      'export': 'エクスポート',
      'import': 'インポート',
      'import_success': 'インポート成功!',
      'import_failed': 'インポート失敗',
      'export_success': 'エクスポート成功!',
      'export_failed': 'エクスポート失敗',
},
    // Rusça (Rusya)
    'ru': {
      'app_name': 'Счётчик',
      'help_title': 'Справка приложения',
      'help_streak_title': 'Что такое серия (Streak)?',
      'help_streak_text': 'При регулярном выполнении целей вы получаете серию. Чем дольше она длится, тем выше мотивация. Выполняйте хотя бы одну цель в день, чтобы поддерживать серию!',
      'help_goal_title': 'Как работают цели?',
      'help_goal_text': 'Можно задать ежедневные, еженедельные или ежемесячные цели. Например: «1000 зикров в день». При достижении целей получаете специальные уведомления и анимации.',
      'help_addzikr_title': 'Как добавить зикр?',
      'help_addzikr_text': 'Нажмите имя зикра на главном экране для выбора. Выберите из существующих или создайте свой через «Добавить новый зикр».',
      'help_toggles_title': 'Кнопки-переключатели',
      'help_toggles_text': 'Используйте нижние элементы (вибрация, звук, конфетти) для мгновенного переключения и персонализации.',
      'enable_reminder': 'Включить напоминание',
      'reminder_enabled': 'Напоминание активно',
      'reminder_disabled': 'Напоминание неактивно',
      'reminder_set_success': 'Напоминание установлено!',
      'reminder_set_fail': 'Не удалось установить напоминание. Предоставьте разрешения.',
      'reminder_cancelled': 'Напоминание отменено.',
      'test_notification_sent': 'Тестовое уведомление отправлено!',
      'test': 'Тест',
      'close': 'Закрыть',
      'counter': 'Счётчик',
      'target': 'Цель',
      'reset': 'Сброс',
      'continue': 'Продолжить',
      'cancel': 'Отмена',
      'ok': 'OK',
      'settings': 'Настройки',
      'theme': 'Тема',
      'language': 'Язык',
      'vibration': 'Вибрация',
      'sound': 'Звук',
      'success_title': 'Отлично! 🎉',
      'success_message': 'Цель достигнута!',
      'goals': 'Цели',
      'dailyGoal': 'Ежедневная цель',
      'weeklyGoal': 'Еженедельная цель',
      'monthlyGoal': 'Ежемесячная цель',
      'progress': 'Прогресс',
      'statistics': 'Статистика',
      'today': 'Сегодня',
      'total': 'Всего',
      'streak': 'Серия',
      'consecutiveDays': 'Дней подряд',
      'last7Days': 'Последние 7 дней',
      'days': 'дней',
      'select_zikr': 'Выбрать Зикр',
      'add_zikr': 'Добавить Зикр',
      'custom_zikrs': 'Пользовательские Зикры',
      'zikr_name_ar': 'Арабское Имя',
      'zikr_name_tr': 'Турецкое Имя',
      'zikr_name_en': 'Английское Имя',
      'zikr_name_id': 'Индонезийское Имя',
      'zikr_name_ur': 'Имя на Урду',
      'zikr_name_bn': 'Бенгальское Имя',
      'zikr_name_ms': 'Малайское Имя',
      'zikr_name_fa': 'Персидское Имя',
      'zikr_name_fr': 'Французское Имя',
      'zikr_name_zh': 'Китайское Имя',
      'zikr_name_ja': 'Японское Имя',
      'zikr_name_ru': 'Русское Имя',
      'zikr_name_de': 'Немецкое Имя',
      'zikr_name_sw': 'Имя на Суахили',
      'zikr_name_ha': 'Имя на Хауса',
      'set_target': 'Установить Цель',
      'quick_select': 'Быстрый Выбор',
      'custom_target': 'Пользовательская Цель',
      'enter_target': 'Введите целевой номер',
      'setGoal': 'Установить Цель',
      'goalCompleted': 'Цель Достигнута! 🎯',
      'zikr_count': 'Зикр',
      'edit': 'Редактировать',
      'delete': 'Удалить',
      'save': 'Сохранить',
      'trophies': 'Трофеи',
      'streak_continues': 'серия продолжается',
      'new_record': 'Новый рекорд!',
      'achievement_streaks': 'Серии Достижений',
      'weeks': 'Недели',
      'months': 'Месяцы',
      'last_4_weeks': 'Последние 4 Недели',
      'last_12_months': 'Последние 12 Месяцев',
      'optional': 'Необязательно',
      'required': 'обязательно',
      'transliteration': 'Транслитерация',
      'version': 'Версия 1.0.0',
      'support_us': 'Поддержите нас',
      'support_description': 'Помогите нам сохранить это приложение бесплатным, просмотрев короткую рекламу. Ваша поддержка очень важна!',
      'watch_ad': 'Смотреть Рекламу',
      'ad_not_ready': 'Реклама не готова, попробуйте еще раз',
      'thank_you_support': 'Спасибо за вашу поддержку! 🙏',
      'features': 'Функции',
      'feature_goals': 'Ежедневные, Еженедельные, Ежемесячные Цели',
      'feature_statistics': 'Подробная Статистика',
      'feature_widget': 'Виджет Главного Экрана',
      'feature_languages': 'Поддержка 15 Языков',
          'contact': 'Контакты',
      'source_code': 'Исходный Код',
      'default_count': 'Количество по умолчанию',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Увеличить счётчик',
      'resetCounter': 'Сбросить счётчик',
      'changeTarget': 'Изменить цель',
      'vibrationOn': 'Вибрация включена',
      'vibrationOff': 'Вибрация выключена',
      'soundOn': 'Звук включён',
      'soundOff': 'Звук выключен',
      'about': 'О приложении',
      'confettiOn': 'Конфетти включено',
      'confettiOff': 'Конфетти выключено',
      'setReminder': 'Установить напоминание',
      'cancelReminder': 'Отмена',
      'mon': 'Пн',
      'tue': 'Вт',
      'wed': 'Ср',
      'thu': 'Чт',
      'fri': 'Пт',
      'sat': 'Сб',
      'sun': 'Вс',
      'day_streak': 'Ежедневная серия',
      'new_best': 'Новый рекорд!',
      'completed_today': 'Завершено сегодня',
      'tts': 'Голосовое чтение',
      'ttsOn': 'Голосовое чтение включено',
      'ttsOff': 'Голосовое чтение выключено',
      'speak_zikr': 'Читать Зикр',
      'export': 'Экспорт',
      'import': 'Импорт',
      'import_success': 'Импорт успешен!',
      'import_failed': 'Импорт не удался',
      'export_success': 'Экспорт успешен!',
      'export_failed': 'Экспорт не удался',
},
    // Almanca (Almanya)
    'de': {
      'app_name': 'Zähler',
      'help_title': 'App-Hilfe',
      'help_streak_title': 'Was ist eine Serie (Streak)?',
      'help_streak_text': 'Wenn du regelmäßig Ziele erreichst, erhältst du eine Serie. Je länger du sie hältst, desto größer die Motivation. Erreiche täglich mindestens ein Ziel, um die Serie aktiv zu halten!',
      'help_goal_title': 'Wie funktionieren Ziele?',
      'help_goal_text': 'Du kannst tägliche, wöchentliche oder monatliche Ziele festlegen. Z. B.: „1000 Dhikr pro Tag“. Beim Erreichen erhältst du spezielle Benachrichtigungen und Animationen.',
      'help_addzikr_title': 'Wie fügt man einen Dhikr hinzu?',
      'help_addzikr_text': 'Tippe auf den Dhikr-Namen auf dem Startbildschirm, um die Auswahl zu öffnen. Wähle einen vorhandenen Dhikr oder erstelle einen neuen über „Neuen Dhikr hinzufügen“.',
      'help_toggles_title': 'Umschaltknöpfe',
      'help_toggles_text': 'Nutze die unteren Schalter (Vibration, Ton, Konfetti), um Funktionen sofort zu wechseln und die Erfahrung zu personalisieren.',
      'enable_reminder': 'Erinnerung aktivieren',
      'reminder_enabled': 'Erinnerung aktiv',
      'reminder_disabled': 'Erinnerung inaktiv',
      'reminder_set_success': 'Erinnerung gesetzt!',
      'reminder_set_fail': 'Erinnerung konnte nicht gesetzt werden. Bitte Berechtigungen erteilen.',
      'reminder_cancelled': 'Erinnerung abgebrochen.',
      'test_notification_sent': 'Testbenachrichtigung gesendet!',
      'test': 'Test',
      'close': 'Schließen',
      'counter': 'Zähler',
      'target': 'Ziel',
      'reset': 'Zurücksetzen',
      'continue': 'Weiter',
      'cancel': 'Abbrechen',
      'ok': 'OK',
      'settings': 'Einstellungen',
      'theme': 'Thema',
      'language': 'Sprache',
      'vibration': 'Vibration',
      'sound': 'Ton',
      'success_title': 'Ausgezeichnet! 🎉',
      'success_message': 'Ziel erreicht!',
      'goals': 'Ziele',
      'dailyGoal': 'Tägliches Ziel',
      'weeklyGoal': 'Wöchentliches Ziel',
      'monthlyGoal': 'Monatliches Ziel',
      'progress': 'Fortschritt',
      'statistics': 'Statistiken',
      'today': 'Heute',
      'total': 'Gesamt',
      'streak': 'Serie',
      'consecutiveDays': 'Aufeinanderfolgende Tage',
      'last7Days': 'Letzte 7 Tage',
      'days': 'Tage',
      'select_zikr': 'Dhikr Auswählen',
      'add_zikr': 'Dhikr Hinzufügen',
      'custom_zikrs': 'Benutzerdefinierte Dhikrs',
      'zikr_name_ar': 'Arabischer Name',
      'zikr_name_tr': 'Türkischer Name',
      'zikr_name_en': 'Englischer Name',
      'zikr_name_id': 'Indonesischer Name',
      'zikr_name_ur': 'Urdu-Name',
      'zikr_name_bn': 'Bengalischer Name',
      'zikr_name_ms': 'Malaiischer Name',
      'zikr_name_fa': 'Persischer Name',
      'zikr_name_fr': 'Französischer Name',
      'zikr_name_zh': 'Chinesischer Name',
      'zikr_name_ja': 'Japanischer Name',
      'zikr_name_ru': 'Russischer Name',
      'zikr_name_de': 'Deutscher Name',
      'zikr_name_sw': 'Swahili-Name',
      'zikr_name_ha': 'Hausa-Name',
      'set_target': 'Ziel Festlegen',
      'quick_select': 'Schnellauswahl',
      'custom_target': 'Benutzerdefiniertes Ziel',
      'enter_target': 'Zielnummer eingeben',
      'setGoal': 'Ziel Festlegen',
      'goalCompleted': 'Ziel Erreicht! 🎯',
      'zikr_count': 'Dhikr',
      'edit': 'Bearbeiten',
      'delete': 'Löschen',
      'save': 'Speichern',
      'trophies': 'Trophäen',
      'streak_continues': 'Serie geht weiter',
      'new_record': 'Neuer Rekord!',
      'achievement_streaks': 'Erfolgsserien',
      'weeks': 'Wochen',
      'months': 'Monate',
      'last_4_weeks': 'Letzte 4 Wochen',
      'last_12_months': 'Letzte 12 Monate',
      'optional': 'Optional',
      'required': 'erforderlich',
      'transliteration': 'Transliteration',
      'version': 'Version 1.0.0',
      'support_us': 'Unterstützen Sie uns',
      'support_description': 'Helfen Sie uns, diese App kostenlos zu halten, indem Sie eine kurze Werbung ansehen. Ihre Unterstützung bedeutet viel!',
      'watch_ad': 'Werbung Ansehen',
      'ad_not_ready': 'Werbung nicht bereit, bitte versuchen Sie es erneut',
      'thank_you_support': 'Vielen Dank für Ihre Unterstützung! 🙏',
      'features': 'Funktionen',
      'feature_goals': 'Tägliche, Wöchentliche, Monatliche Ziele',
      'feature_statistics': 'Detaillierte Statistiken',
      'feature_widget': 'Startbildschirm-Widget',
      'feature_languages': 'Unterstützung für 15 Sprachen',
          'contact': 'Kontakt',
      'source_code': 'Quellcode',
      'default_count': 'Standardanzahl',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Zähler erhöhen',
      'resetCounter': 'Zähler zurücksetzen',
      'changeTarget': 'Ziel ändern',
      'vibrationOn': 'Vibration an',
      'vibrationOff': 'Vibration aus',
      'soundOn': 'Ton an',
      'soundOff': 'Ton aus',
      'about': 'Über',
      'confettiOn': 'Konfetti an',
      'confettiOff': 'Konfetti aus',
      'setReminder': 'Erinnerung festlegen',
      'cancelReminder': 'Abbrechen',
      'mon': 'Mo',
      'tue': 'Di',
      'wed': 'Mi',
      'thu': 'Do',
      'fri': 'Fr',
      'sat': 'Sa',
      'sun': 'So',
      'day_streak': 'Tägliche Serie',
      'new_best': 'Neue Bestleistung!',
      'completed_today': 'Heute abgeschlossen',
      'tts': 'Sprachausgabe',
      'ttsOn': 'Sprachausgabe an',
      'ttsOff': 'Sprachausgabe aus',
      'speak_zikr': 'Dhikr vorlesen',
      'export': 'Exportieren',
      'import': 'Importieren',
      'import_success': 'Import erfolgreich!',
      'import_failed': 'Import fehlgeschlagen',
      'export_success': 'Export erfolgreich!',
      'export_failed': 'Export fehlgeschlagen',
},
    // Svahili (Doğu Afrika)
    'sw': {
      'app_name': 'Kihesabu',
      'help_title': 'Msaada wa Programu',
      'help_streak_title': 'Streak ni nini?',
      'help_streak_text': 'Unapokamilisha malengo mara kwa mara, unapata mfululizo. Unapoudumisha kwa muda mrefu, motisha huongezeka. Kamilisha angalau lengo moja kila siku kudumisha mfululizo!',
      'help_goal_title': 'Malengo hufanyaje kazi?',
      'help_goal_text': 'Unaweza kuweka malengo ya kila siku, kila wiki au kila mwezi. Mfano: "Dhikri 1000 kwa siku". Ukifikia malengo, utapata arifa na uhuishaji maalum.',
      'help_addzikr_title': 'Jinsi ya kuongeza Dhikr?',
      'help_addzikr_text': 'Gonga jina la dhikr kwenye skrini kuu kufungua uteuzi. Chagua kutoka kwa dhikr zilizopo au unda yako kupitia "Ongeza Dhikr Mpya".',
      'help_toggles_title': 'Vifungo vya kubadilisha',
      'help_toggles_text': 'Tumia vidhibiti vya chini (Mtetemo, Sauti, Konfeti) kuwasha/kuzima mara moja na kubinafsisha matumizi.',
      'enable_reminder': 'Washa Ukumbusho',
      'reminder_enabled': 'Ukumbusho umewezeshwa',
      'reminder_disabled': 'Ukumbusho umezimwa',
      'reminder_set_success': 'Ukumbusho umewekwa!',
      'reminder_set_fail': 'Imeshindikana kuweka ukumbusho. Tafadhali toa ruhusa.',
      'reminder_cancelled': 'Ukumbusho umefutwa.',
      'test_notification_sent': 'Arifa ya majaribio imetumwa!',
      'test': 'Jaribu',
      'close': 'Funga',
      'counter': 'Kihesabu',
      'target': 'Lengo',
      'reset': 'Weka Upya',
      'continue': 'Endelea',
      'cancel': 'Ghairi',
      'ok': 'Sawa',
      'settings': 'Mipangilio',
      'theme': 'Mandhari',
      'language': 'Lugha',
      'vibration': 'Mtetemo',
      'sound': 'Sauti',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'Lengo limefikiwa!',
      'goals': 'Malengo',
      'dailyGoal': 'Lengo la Kila Siku',
      'weeklyGoal': 'Lengo la Kila Wiki',
      'monthlyGoal': 'Lengo la Kila Mwezi',
      'progress': 'Maendeleo',
      'statistics': 'Takwimu',
      'today': 'Leo',
      'total': 'Jumla',
      'streak': 'Mfululizo',
      'consecutiveDays': 'Siku za mfululizo',
      'last7Days': 'Siku 7 Zilizopita',
      'days': 'siku',
      'select_zikr': 'Chagua Dhikr',
      'add_zikr': 'Ongeza Dhikr',
      'custom_zikrs': 'Dhikr Maalum',
      'zikr_name_ar': 'Jina la Kiarabu',
      'zikr_name_tr': 'Jina la Kituruki',
      'zikr_name_en': 'Jina la Kiingereza',
      'zikr_name_id': 'Jina la Kiindonesia',
      'zikr_name_ur': 'Jina la Kiurdu',
      'zikr_name_bn': 'Jina la Kibengali',
      'zikr_name_ms': 'Jina la Kimalesia',
      'zikr_name_fa': 'Jina la Kiajemi',
      'zikr_name_fr': 'Jina la Kifaransa',
      'zikr_name_zh': 'Jina la Kichina',
      'zikr_name_ja': 'Jina la Kijapani',
      'zikr_name_ru': 'Jina la Kirusi',
      'zikr_name_de': 'Jina la Kijerumani',
      'zikr_name_sw': 'Jina la Kiswahili',
      'zikr_name_ha': 'Jina la Kihausa',
      'set_target': 'Weka Lengo',
      'quick_select': 'Uchaguzi wa Haraka',
      'custom_target': 'Lengo Maalum',
      'enter_target': 'Weka nambari ya lengo',
      'setGoal': 'Weka Lengo',
      'goalCompleted': 'Lengo Limefikiwa! 🎯',
      'zikr_count': 'Dhikr',
      'edit': 'Hariri',
      'delete': 'Futa',
      'save': 'Hifadhi',
      'trophies': 'Tuzo',
      'streak_continues': 'mfululizo unaendelea',
      'new_record': 'Rekodi mpya!',
      'achievement_streaks': 'Mfululizo wa Mafanikio',
      'weeks': 'Wiki',
      'months': 'Miezi',
      'last_4_weeks': 'Wiki 4 Zilizopita',
      'last_12_months': 'Miezi 12 Iliyopita',
      'optional': 'Hiari',
      'required': 'inahitajika',
      'transliteration': 'Tafsiri ya Herufi',
      'version': 'Toleo 1.0.0',
      'support_us': 'Tusaidie',
      'support_description': 'Tusaidie kuweka programu hii bure kwa kutazama tangazo fupi. Msaada wako una maana sana!',
      'watch_ad': 'Tazama Tangazo',
      'ad_not_ready': 'Tangazo halijawa tayari, tafadhali jaribu tena',
      'thank_you_support': 'Asante kwa msaada wako! 🙏',
      'features': 'Vipengele',
      'feature_goals': 'Malengo ya Kila Siku, Kila Wiki, Kila Mwezi',
      'feature_statistics': 'Takwimu za Kina',
      'feature_widget': 'Widget ya Skrini Kuu',
      'feature_languages': 'Msaada wa Lugha 15',
          'contact': 'Wasiliana',
      'source_code': 'Msimbo wa Chanzo',
      'default_count': 'Idadi ya Chaguo-msingi',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Ongeza kihesabu',
      'resetCounter': 'Weka upya kihesabu',
      'changeTarget': 'Badilisha lengo',
      'vibrationOn': 'Mtetemo umewashwa',
      'vibrationOff': 'Mtetemo umezimwa',
      'soundOn': 'Sauti imewashwa',
      'soundOff': 'Sauti imezimwa',
      'about': 'Kuhusu',
      'confettiOn': 'Konfeti imewashwa',
      'confettiOff': 'Konfeti imezimwa',
      'setReminder': 'Weka Ukumbusho',
      'cancelReminder': 'Ghairi',
      'mon': 'Jtu',
      'tue': 'Jnn',
      'wed': 'Jtn',
      'thu': 'Alh',
      'fri': 'Iju',
      'sat': 'Jmm',
      'sun': 'Jpg',
      'day_streak': 'Mfululizo wa Kila Siku',
      'new_best': 'Rekodi Mpya Bora!',
      'completed_today': 'Imekamilika Leo',
      'tts': 'Usomaji wa Sauti',
      'ttsOn': 'Usomaji wa sauti umewashwa',
      'ttsOff': 'Usomaji wa sauti umezimwa',
      'speak_zikr': 'Soma Dhikr',
      'export': 'Hamisha Nje',
      'import': 'Hamisha Ndani',
      'import_success': 'Uhamishaji umefanikiwa!',
      'import_failed': 'Uhamishaji umeshindwa',
      'export_success': 'Uhamishaji nje umefanikiwa!',
      'export_failed': 'Uhamishaji nje umeshindwa',
},
    // Hausa (Batı Afrika)
    'ha': {
      'app_name': 'Mai Ƙidaya',
      'help_title': 'Taimakon App',
      'help_streak_title': 'Menene Streak?',
      'help_streak_text': 'Idan kana cika manufofi a kai a kai, kana samun jeri. Tsawon lokacinda ya daɗe, ƙwarin gwiwa yana ƙaruwa. Kammala aƙalla manufa guda a rana don kiyaye jerin!',
      'help_goal_title': 'Yaya manufofi ke aiki?',
      'help_goal_text': 'Za ka iya saita manufofin yau da kullum, na kowane mako ko wata. Misali: "Zikiri 1000 a rana". Idan ka cimma, za ka sami sanarwa da nune-nunen musamman.',
      'help_addzikr_title': 'Yadda za a ƙara Zikiri?',
      'help_addzikr_text': 'Danna sunan zikiri a allon farko don buɗe zaɓin. Zaɓi daga waɗanda ake da su ko ƙirƙiri naka ta "Ƙara Sabon Zikiri".',
      'help_toggles_title': 'Maɓallan canjawa',
      'help_toggles_text': 'Yi amfani da maɓallan ƙasa (Girgiza, Sauti, Konfeti) don kunnawa/katsewa nan take da daidaita kwarewa.',
      'enable_reminder': ' kunna Tunatarwa',
      'reminder_set_success': 'An saita tunatarwa!',
      'reminder_set_fail': 'An kasa saita tunatarwa. Don Allah bayar da izini.',
      'reminder_cancelled': 'An soke tunatarwa.',
      'test_notification_sent': 'An aika sanarwar gwaji!',
      'test': 'Gwaji',
      'close': 'Rufe',
      'counter': 'Mai Ƙidaya',
      'target': 'Manufa',
      'reset': 'Sake Saita',
      'continue': 'Ci gaba',
      'cancel': 'Soke',
      'ok': 'To',
      'settings': 'Saitunan',
      'theme': 'Jigo',
      'language': 'Harshe',
      'vibration': 'Girgiza',
      'sound': 'Sauti',
      'success_title': 'MashaAllah! 🎉',
      'success_message': 'An cimma manufa!',
      'goals': 'Manufofi',
      'dailyGoal': 'Manufar Yau da Kullum',
      'weeklyGoal': 'Manufar Mako-mako',
      'monthlyGoal': 'Manufar Wata-wata',
      'progress': 'Ci gaba',
      'statistics': 'Kididdiga',
      'today': 'Yau',
      'total': 'Jimla',
      'streak': 'Jeri',
      'consecutiveDays': 'Kwanaki a jere',
      'last7Days': 'Kwanaki 7 da suka gabata',
      'days': 'kwanaki',
      'select_zikr': 'Zaɓi Zikiri',
      'add_zikr': 'Ƙara Zikiri',
      'custom_zikrs': 'Zikiri na Musamman',
      'zikr_name_ar': 'Sunan Larabci',
      'zikr_name_tr': 'Sunan Turkiyya',
      'zikr_name_en': 'Sunan Turanci',
      'zikr_name_id': 'Sunan Indonesiya',
      'zikr_name_ur': 'Sunan Urdu',
      'zikr_name_bn': 'Sunan Bengali',
      'zikr_name_ms': 'Sunan Malay',
      'zikr_name_fa': 'Sunan Farisa',
      'zikr_name_fr': 'Sunan Faransanci',
      'zikr_name_zh': 'Sunan Sinanci',
      'zikr_name_ja': 'Sunan Jafananci',
      'zikr_name_ru': 'Sunan Rashanci',
      'zikr_name_de': 'Sunan Jamusanci',
      'zikr_name_sw': 'Sunan Swahili',
      'zikr_name_ha': 'Sunan Hausa',
      'set_target': 'Saita Manufa',
      'quick_select': 'Zaɓi da Sauri',
      'custom_target': 'Manufa ta Musamman',
      'enter_target': 'Shigar da lambar manufa',
      'setGoal': 'Saita Manufa',
      'goalCompleted': 'An Cimma Manufa! 🎯',
      'zikr_count': 'Zikiri',
      'edit': 'Gyara',
      'delete': 'Goge',
      'save': 'Ajiye',
      'trophies': 'Kyautuka',
      'streak_continues': 'jeri yana ci gaba',
      'new_record': 'Sabon rikodin!',
      'achievement_streaks': 'Jerin Nasara',
      'weeks': 'Makonni',
      'months': 'Watanni',
      'last_4_weeks': 'Makonni 4 da suka gabata',
      'last_12_months': 'Watanni 12 da suka gabata',
      'optional': 'Na Zaɓi',
      'required': 'ana bukata',
      'transliteration': 'Fassarar Haruffa',
      'version': 'Sigar 1.0.0',
      'support_us': 'Tallafa Mana',
      'support_description': 'Taimaka mana mu kiyaye wannan app kyauta ta hanyar kallon gajeren talla. Goyon bayanku yana da mahimmanci!',
      'watch_ad': 'Kalli Talla',
      'ad_not_ready': 'Talla ba ta shirye ba, don Allah sake gwadawa',
      'thank_you_support': 'Mun gode da goyon bayanku! 🙏',
      'features': 'Fasaloli',
      'feature_goals': 'Manufofin Yau da Kullum, Mako-mako, Wata-wata',
      'feature_statistics': 'Cikakkun Kididdiga',
      'feature_widget': 'Widget na Babban Allo',
      'feature_languages': 'Tallafin Harsuna 15',
          'contact': 'Tuntuɓe mu',
      'source_code': 'Lambar Tushe',
      'default_count': 'Adadin Tsoho',
      'arabic': 'العربية',
      'turkish': 'Türkçe',
      'english': 'English',
      'indonesian': 'Bahasa Indonesia',
      'incrementCounter': 'Ƙara mai ƙidaya',
      'resetCounter': 'Sake saita mai ƙidaya',
      'changeTarget': 'Canja manufa',
      'vibrationOn': 'Girgiza na aiki',
      'vibrationOff': 'Girgiza ya tsaya',
      'soundOn': 'Sauti na aiki',
      'soundOff': 'Sauti ya tsaya',
      'about': 'Game da',
      'confettiOn': 'Taurari na aiki',
      'confettiOff': 'Taurari ya tsaya',
      'setReminder': 'Saita Tunawa',
      'cancelReminder': 'Soke',
      'mon': 'Lit',
      'tue': 'Tal',
      'wed': 'Lar',
      'thu': 'Alh',
      'fri': 'Jum',
      'sat': 'Asa',
      'sun': 'Lha',
      'day_streak': 'Jerin Yau da Kullum',
      'new_best': 'Sabon Mafi Kyau!',
      'completed_today': 'An Kammala Yau',
      'tts': 'Karatu da Murya',
      'ttsOn': 'Karatu da murya na aiki',
      'ttsOff': 'Karatu da murya ya tsaya',
      'speak_zikr': 'Karanta Zikiri',
      'export': 'Fitar da Bayanai',
      'import': 'Shigar da Bayanai',
      'import_success': 'Shigarwa ta yi nasara!',
      'import_failed': 'Shigarwa ta kasa',
      'export_success': 'Fitarwa ta yi nasara!',
      'export_failed': 'Fitarwa ta kasa',
      'developer_name': 'Caner Erdem',
      'developer_title': 'Geliştirici',
      'developer_website': 'www.mcanererdem.com',
      'developer_email': 'info@mcanererdem.com',
      'developer_github': 'github.com/mcanererdem',
},
  };

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }

  String get appName => translate('app_name');
  String get counter => translate('counter');
  String get target => translate('target');
  String get reset => translate('reset');
  String get continueText => translate('continue');
  String get cancel => translate('cancel');
  String get ok => translate('ok');
  String get settings => translate('settings');
  String get theme => translate('theme');
  String get language => translate('language');
  String get vibration => translate('vibration');
  String get sound => translate('sound');
  String get selectZikr => translate('select_zikr');
  String get addZikr => translate('add_zikr');
  String get customZikrs => translate('custom_zikrs');
  String get zikrNameAr => translate('zikr_name_ar');
  String get zikrNameTr => translate('zikr_name_tr');
  String get zikrNameEn => translate('zikr_name_en');
  String get defaultCount => translate('default_count');
  String get setTarget => translate('set_target');
  String get quickSelect => translate('quick_select');
  String get customTarget => translate('custom_target');
  String get enterTarget => translate('enter_target');
  String get successTitle => translate('success_title');
  String get successMessage => translate('success_message');
  String get zikrCount => translate('zikr_count');
  String get edit => translate('edit');
  String get delete => translate('delete');
  String get save => translate('save');
  String get arabic => translate('arabic');
  String get turkish => translate('turkish');
  String get english => translate('english');
  String get indonesian => translate('indonesian');
  String get incrementCounter => translate('incrementCounter');
  String get resetCounter => translate('resetCounter');
  String get changeTarget => translate('changeTarget');
  String get vibrationOn => translate('vibrationOn');
  String get vibrationOff => translate('vibrationOff');
  String get soundOn => translate('soundOn');
  String get soundOff => translate('soundOff');
  String get about => translate('about');
  String get confettiOn => translate('confettiOn');
  String get confettiOff => translate('confettiOff');
  String get setReminder => translate('setReminder');
  String get cancelReminder => translate('cancelReminder');
  String get goals => translate('goals');
  String get dailyGoal => translate('dailyGoal');
  String get weeklyGoal => translate('weeklyGoal');
  String get monthlyGoal => translate('monthlyGoal');
  String get setGoal => translate('setGoal');
  String get goalCompleted => translate('goalCompleted');
  String get progress => translate('progress');
  String get statistics => translate('statistics');
  String get today => translate('today');
  String get total => translate('total');
  String get streak => translate('streak');
  String get consecutiveDays => translate('consecutiveDays');
  String get last7Days => translate('last7Days');
  String get days => translate('days');
  String get mon => translate('mon');
  String get tue => translate('tue');
  String get wed => translate('wed');
  String get thu => translate('thu');
  String get fri => translate('fri');
  String get sat => translate('sat');
  String get sun => translate('sun');
  String get trophies => translate('trophies');
  String get reminderEnabled => translate('reminder_enabled');
  String get reminderDisabled => translate('reminder_disabled');
}
